### ISSUE TITLE
Clarify the status of this project

### ISSUE THREAD

**Issue by orf** [fenichelar/ember-simple-auth-token#102]
Hi,
We've been using this library in our application for a while and are very happy with it. However Ember 2 is out, and now ESA has updated this is the last dependency we are waiting on.

I notice the last commit was on the 23rd of July, and being Novemeber now can we have a statement from the owner regarding the future of this library?

If the author has abandoned it then perhaps a community effort can be organised to take over? This library seems to be pretty popular.

**Comment by jpadilla** [comment]
Definitely not abandoned. Currently working on other projects that aren't using this so I'm not as active, but I've been around and keeping an eye on the activity regarding adding support for newer versions.
