### ISSUE TITLE
Detecting when the backend is unreachable 

### ISSUE THREAD

**Issue by angelosarto** [fenichelar/ember-simple-auth-token#105]
When calling the authenticate method and the backend is down the authenticate method fails since the preflight OPTIONS request is not successful.

The details of this error does not seem to pass back through to authenticate e.g. in the controller this code will Result in the reason being empty. 

'this.get('session').authenticate(authenticator, credentials).catch((reason) => {'

Is it possible to return a bit more information in this case?  It seems like this is a common enough event (especially in the case of apps which have some offline capability)

**Comment by erichaus** [comment]
@angelosarto you may want to open this in the main https://github.com/simplabs/ember-simple-auth repo...

**Comment by jpadilla** [comment]
This is probably out of the scope of this package.
