### ISSUE TITLE
Push new version to npmjs

### ISSUE THREAD

**Issue by gonvaled** [fenichelar/ember-simple-auth-token#111]
Last published version is 0.7.3, from a couple of months ago:

https://www.npmjs.com/package/ember-cli-simple-auth-token

**Comment by jrjohnson** [comment]
@gonvaled my understanding is that a new version is imminent.  0.7.3 is stable with ember-cli-simple-auth 0.8.0, but now that #100 is merged we will see a new version very soon once some other cleanup is done.

@jpadilla is there a list of tasks somewhere that we can help with?

**Comment by gonvaled** [comment]
@jrjohnson I see. I was not able to get ember-cli-simple-auth-token working because it is incompatible with current ember-simple-auth, and I do not know how npm install from source.

**Comment by gonvaled** [comment]
Never mind, I think it is possible to install it with:

```
ember install ember-simple-auth  # install current version of ember-simple-auth
npm install --save-dev https://github.com/jpadilla/ember-cli-simple-auth-token.git  # master of ember-cli-simple-auth-token
```

Maybe the README should be updated with this? Usually people install stuff with ember / npm + name of package, not with direct repo URL.

I haven't tested it though. I'll do that now.

**Comment by listepo** [comment]
+1

**Comment by mohlek** [comment]
+1

**Comment by jpadilla** [comment]
Yeah I get it, I'll push a new version sometime this week. The +1 can stop now.

**Comment by gonvaled** [comment]
Just for sake of completeness: `ember-simple-auth-token` is working for me now in development environment, by using a full URL specifier, but [I am unable](https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/119) [to push to Heroku](http://stackoverflow.com/q/34475567/647991)

**Comment by rmzr7** [comment]
+1

**Comment by jpadilla** [comment]
Just published v1.0.0 https://www.npmjs.com/package/ember-simple-auth-token

**Comment by xcambar** [comment]
:tada: Thanks @jpadilla!

**Comment by acorncom** [comment]
Agreed, thanks for all the work :+1:
