### ISSUE TITLE
404 on ember install

### ISSUE THREAD

**Issue by neilyoung** [fenichelar/ember-simple-auth-token#115]
ember install ember-simple-auth-token
version: 1.13.13
Registry returned 404 for GET on https://registry.npmjs.org/ember-simple-auth-token

**Comment by eluciano11** [comment]
Hi, try running `ember-cli-simple-auth-token`. This will install ember-cli-simple-auth on the 0.7.1 version. This version is not working with `ember-simple-auth` version 1.0.0 so you should use 0.8.0.

**Comment by jpadilla** [comment]
Just published v1.0.0 https://www.npmjs.com/package/ember-simple-auth-token
