### ISSUE TITLE
Provide a reason of failed authentication

### ISSUE THREAD

**Issue by sammy007** [fenichelar/ember-simple-auth-token#116]
I am not sure it's appropriate place, maybe issue must be submitted to simple-auth. Currently the only way to determine that auth failed is:

``` javascript
this.get('session').authenticate('authenticator:jwt', credentials).catch((reason) => {
  this.set('loginFailed', true);
});
```

The `reason` is always empty and there is no way to check if user was found or not, password correct or not. I'd like to inspect http code and provide appropriate error message to a user. Is it possible?

**Comment by eluciano11** [comment]
Hi, I just tried this and it worked for me.

<img width="1214" alt="screen shot 2015-12-30 at 11 39 39 pm" src="https://cloud.githubusercontent.com/assets/6109151/12060855/c90d9572-af4e-11e5-91b5-a1b1dbf674e9.png">

**Comment by sammy007** [comment]
@eluciano11 can you post some code?

**Comment by eluciano11** [comment]
yes

```
  actions: {
    login(data) {
      const controller = this.controllerFor('login');

      controller.set('isLoginIn', true);
      this.get('session').authenticate('authenticator:jwt', data).catch(err => {
        console.log('hey', err);

        controller.set('fieldErrors', err);
        controller.set('isLoginIn', false);
      });
    }
  }
```

**Comment by eluciano11** [comment]
You can open your developer tools in chrome and go to the network tab to make sure that your backend is sending the information about the fields that had errors on the validation.

**Comment by sammy007** [comment]
Still not works for me :( I tried both controller and route actions, but actually there is no difference anyway. My API is on another domain, maybe this is an issue.

**Comment by sammy007** [comment]
> You can open your developer tools in chrome and go to the network tab to make sure that your backend is sending information about the fields that had errors on the validation.

My backed just respond with empty body and 500, 400 & 401 errors. And all I want is to check code and show if auth failed or it's a server error.

**Comment by eluciano11** [comment]
Ahh, yeah, I think that's the problem. It's up to the backend to tell what went wrong in the authentication so if you want to display the error information it shouldn't return an empty body.

Example:
<img width="607" alt="screen shot 2015-12-31 at 12 08 47 am" src="https://cloud.githubusercontent.com/assets/6109151/12061048/c0163a38-af52-11e5-88ae-bb131f00716e.png">
