### ISSUE TITLE
Allow to pass extra credentials to backend server

### ISSUE THREAD

**Issue by sammy007** [fenichelar/ember-simple-auth-token#117]
I tried to pass extra params along with login and password and it seems authenticator cutting everything.

``` javascript
const credentials = this.getProperties('identification', 'password', 'extra');
```

Sure, I can override `getAuthenticateData` but please consider passing extra params by default.

**Comment by samtes** [comment]
That feature would be very helpful.

**Comment by sammy007** [comment]
You can create your own authenticator:

``` javascript
// app/authenticators/my-jwt.js
import Base from 'ember-simple-auth-token/authenticators/jwt';

export default Base.extend({
  getAuthenticateData(credentials) {
    const authentication = {
      ['extra']: credentials.extra, 
      [this.passwordField]: credentials.password,
      [this.identificationField]: credentials.identification
    };
    return authentication;
  }
});
```

personally I think that default implementation should pass all available properties.

**Comment by samtes** [comment]
Thx! But what happens when there is an update to this addon?

**Comment by sammy007** [comment]
Everything can happen, if this is public api everything _should_ be fine, I already forgot public this method or not.

**Comment by eluciano11** [comment]
hi @samtes and @sammy007 `getAuthenticateData` is a public method. You're safe to use it.

@sammy007 thank you for your help!
