### ISSUE TITLE
Cannot get custom data from session.data attribute

### ISSUE THREAD

**Issue by danr1979** [fenichelar/ember-simple-auth-token#120]
Hi.

I'm running ember-simple-auth 1.0.1, ember-simple-auth-token 1.0.0 and Ember 2.2.0 with Ember Data 2.2.0.

I've got things working and I'm able to authenticate my Ember app with the server-side PHP API backend running Firebase PHP-JWT. When generating my token on the server side to send back to ember-simple-auth I pass in a "data" attribute containing a "userId" and a few other custom values as follows:

```
$token = array(
    'iss' => env('HOST_NAME'),
    'aud' => env('HOST_NAME'),
    'exp' => $expires,
    'data' => array(
        'userId' => $user->id,
        'roles' => $roles,
        'permissions' => $permissions
    )
);

$jwt = JWT::encode($token, $key, 'HS512');
```

However, in my Ember app if I try to access this data after authenticating like so:

```
this.get('session.data')
```

all I see is the default "authenticated" key with the "exp" and "token" etc inside. How do I go about accessing my custom data values ("userId", "roles" etc)? I've read the documentation but I can't find an example of the data being access, only set.

The response the server is returning when authentication succeeds is as follows:

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwczpcL1wvZGV2LnNlY3VyZS1vcGVyYXRpb25zLmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9kZXYuc2VjdXJlLW9wZXJhdGlvbnMuY29tIiwiZXhwIjoxNDUyNjcyODY2LCJkYXRhIjp7InVzZXJJZCI6IjUiLCJyb2xlcyI6W10sInBlcm1pc3Npb25zIjpbXX19.ivO289WrKI2q-HBLhiHm5tiYZSeqKr1yPueddjW5gZD2s986OaR62sr7fA-Y7tonzj4hmk9H5yCjY1f_hjK2MQ"}

This appears to be a valid token and, interestingly, when the token is passed back to the server in subsequent requests to other API resources I can pick up the "data" fields from it in PHP. This includes my custom fields so they are present in the token but appear to not be being recognized on the client side.

Hopefully this helps to understand what is amiss?

I'd appreciate any help anyone can offer.

Thanks.

**Comment by danr1979** [comment]
Is anyone able to assist me with this issue as I've tried everything and I can't get access to the data I have passed back to the client in the token?

**Comment by eluciano11** [comment]
Hi @danr1979 , according to the `ember-simple-auth` documentation you should be able to access the session data that the authenticator resolved by doing `this.get('session.data.authenticated')`.

http://ember-simple-auth.com/api/classes/SessionService.html

**Comment by eluciano11** [comment]
Closing do to inactivity.

**Comment by danr1979** [comment]
Thanks for your help but this did not work for me. All of my custom data seems to be stripped out.

Should it be possible to get custom data from a token & if so where within the token structure should it be located?

Thanks.

**Comment by waynee-inc** [comment]
I'm sorry, but I have the same question, a mechanism that would just get the token custom data part decoded? or where it is better to implement?

**Comment by benj86** [comment]
Hi. I think the problem is that the token should not be decoded on client-side because it is only for authentication on server-side. If your server get the token it can decode it and you have access to custom data. Only with the token the server can identify who is making a request. So you can make a request to the server, the server decode the token and identifies you and than the server responses with requested data. Since the token is build out of a secret key which is stored server-sided i think it isn't recommended that the client can access any secret data out of the token. Sorry for my english :P

**Comment by danr1979** [comment]
Hi.

In a SPA using JWTs it would be nice to know the logged in user & their roles in order to hide/show certain UI components based on their access level. I would like to pass the roles/userid back in the JWT in order to achieve this. Other articles I have read on JWT suggest this should be possible. Is it just that this library is lacking this functionality at present?

**Comment by danr1979** [comment]
I've found a way of achieving this here:

https://github.com/jpadilla/ember-simple-auth-token/issues/50
