### ISSUE TITLE
Demo login not working

### ISSUE THREAD

**Issue by richardvenneman** [fenichelar/ember-simple-auth-token#123]
Hello,

It seems login functionality in the [demo app](https://jpadilla.github.io/ember-simple-auth-token/#/login) is currently broken. Submitting the login form yields an `404`.

Somehow the `Authorization` header is not present on the request. Please see the following screenshot for more information.

![screen shot 2016-01-27 at 11 36 36](https://cloud.githubusercontent.com/assets/75705/12610865/43326200-c4ea-11e5-9918-cadae6f5ea99.png)

Would love some assistance in this. Still pretty new to Ember and incidentally login functionality 'somehow' also broke in my own app. Have been digging but could not find a solution. But I think it might be related to the missing Authorization header?

**Comment by jpadilla** [comment]
@richardvenneman should be fixed now, forgot to update routes on that server. Thanks for the heads up.

**Comment by richardvenneman** [comment]
Great, thanks!
FYI logging out still leads to a non-existing page (https://jpadilla.github.io/ember-cli-simple-auth-token).

**Comment by jpadilla** [comment]
@richardvenneman fixed
