### ISSUE TITLE
Config via environments

### ISSUE THREAD

**Issue by HelloGrayson** [fenichelar/ember-simple-auth-token#13]
I'm curious why the README suggests configging via `app/index.html` instead of `config/environment.js` - am I missing something? 

http://www.ember-cli.com/#Environments

Thanks :)

**Comment by jpadilla** [comment]
@breerly Good point. That's the way I've always done it with ember-simple-auth. Do you have any examples of achieving the same but with `config/environment.js`?

**Comment by miguelcobain** [comment]
ember-simple-auth now moved from window environments to ember-cli's environment. This addon should do the same.

Maybe this commit gives us a clue: https://github.com/simplabs/ember-cli-simple-auth-devise/commit/d135e3e7e4ba697ecddc316360658638c0eab3fa

**Comment by miguelcobain** [comment]
Right now, as a workaround, changing token initializer to this solves the problem:

``` javascript
import Authenticator from './../authenticators/token';
import Authorizer    from './../authorizers/token';
import ENV from '../config/environment';

export default {
  name: 'simple-auth-token',
  before: 'simple-auth',
  initialize: function(container){
    window.ENV = {
      'simple-auth-token': ENV['simple-auth-token']
    };
    container.register('authorizer:token', Authorizer);
    container.register('authenticator:token', Authenticator);
  }
};

```

You can import ember-cli's environment like that.
This isn't the right way to do it. window variable is nasty. :)

Maybe @marcoow could give us a little help.

**Comment by marcoow** [comment]
@miguelcobain: like you said, this is the way to do it: https://github.com/simplabs/ember-cli-simple-auth-devise/blob/d135e3e7e4ba697ecddc316360658638c0eab3fa/app/initializers/simple-auth-devise.js

**Comment by jpadilla** [comment]
@breerly @miguelcobain @marcoow I've been working into refactoring this to use the new ember-cli's `ember addon` feature as well as adding tests.

I've created a new branch, [refactor](https://github.com/jpadilla/ember-cli-simple-auth-token/tree/refactor) with the current progress which seems to be working on an example project. All tests are passing.

I'd like some feedback on it and if you could try it out and report any weird things, that'd be awesome.

**Comment by miguelcobain** [comment]
It is working great for me!

And it fixed #7 as well. Good job!

Just for the record, added `"ember-cli-simple-auth-token": "jpadilla/ember-cli-simple-auth-token#refactor",` in `package.json` to use this branch.

**Comment by miguelcobain** [comment]
Oops, spoke too soon.

My headers aren't being sent to the server. I'll try to figure out what's the problem.

**Comment by miguelcobain** [comment]
The authorizer wasn't being used.

Had to change environment file from this:

``` javascript
    'simple-auth':{
      authorizer: 'authorizer:token'
    },
```

to this:

``` javascript
    'simple-auth':{
      authorizer: 'simple-auth-authorizer:token'
    },
```

**Comment by jpadilla** [comment]
@miguelcobain I see what happened there. I renamed the default name for the initializers and didn't note that anywhere. That should be enough reason to bump a major version if this makes it. Thoughts so far?

**Comment by miguelcobain** [comment]
Other than that little issue, it is perfect!

I'm extending `TokenAuthenticator` without a problem. #7 is fixed
And it is working with ember-cli environment configuration. :)

Really nice.

**Comment by jpadilla** [comment]
@miguelcobain this are great news. I might then go ahead merge the refactor branch with master, setup Travis, and release to npm this weekend. Closing this for now.
