### ISSUE TITLE
Token refresh with authorization header

### ISSUE THREAD

**Issue by juanramonperez** [fenichelar/ember-simple-auth-token#131]
I can confirm that the authorization header is not present on the request for Refresh Token functionality, is that the correct behavior? If so, how can I add the authorization header on that request?

**Comment by eluciano11** [comment]
Hi @juanramonperez , by default the add-on doesn't add the token to the refresh endpoint request. You can look at the `refreshAccessToken` on the `jwt` authenticator. If you notice, we use the `makeRequest` function. This function is also used on the `authenticate` method on login. You could extend the Authenticator on you application and modify this functions. Currently, these functions are on the private API but were planing to make the public.

You can see an example of extending the Authenticator on #135

Sorry for the late response, please let me know if you found another work around or if this is no longer an issue.

**Comment by juanramonperez** [comment]
Thanks for your response, I will try extending the authenticator

**Comment by bravo-kernel** [comment]
FWIW it would be really nice if sending the current token to the `refresh-token` action as an Authorization header was a configurable (boolean?) option. This would make it instantly compatible with most backend libraries.
