### ISSUE TITLE
How do I transition after a successful login?

### ISSUE THREAD

**Issue by flyrev** [fenichelar/ember-simple-auth-token#132]
I can't find that in the documentation.

**Comment by eluciano11** [comment]
Hi @flyrev, you can add a `sessionAuthenticated` action to your application route and handle the transition there. For this to work you need to extend the `ApplicationRouteMixin`. I do it in may application route so it looks something like this:

``` javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  sessionAuthenticated(res) {
    ...
  },

  sessionInvalidated() {
    ...
  }
});
```

From the `ember-simple-auth` readme:

> The ApplicationRouteMixin automatically maps the session events to the sessionAuthenticated and sessionInvalidated methods it implements. The sessionAuthenticated method will transition to a configurable route while the sessionInvalidated method will reload the page to clear all potentially sensitive data from memory.

**Comment by flyrev** [comment]
Having that code example in the doc would probably be useful. :) It would have saved a lot of time.

**Comment by eluciano11** [comment]
Thanks for the recommendation! We will add it as soon as possible.

**Comment by flyrev** [comment]
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {

gives me

Uncaught ReferenceError: ApplicationRouteMixin is not defined

**Comment by flyrev** [comment]
Oh, never mind. Wrong import.

**Comment by flyrev** [comment]
However, res in your example becomes undefined?

**Comment by eluciano11** [comment]
Ah, sorry I don't really use res. I manage the transition to another route by using `this.transitionTo('someroute')`.
