### ISSUE TITLE
expiresAt in Seconds not Milliseconds 

### ISSUE THREAD

**Issue by digia** [fenichelar/ember-simple-auth-token#133]
JWT expiration timestamp should be set in [seconds](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#page-6). In the current [implementation](https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/jwt.js#L315) getCurrentTime uses date's getTime method which is in milliseconds.  

Is there any reason for this i'm overlooking? Happy to send a PR to fix.

Thanks!

**Comment by jpadilla** [comment]
I don't quite remember the reasoning behind. But maybe @erichonkanen can shine some light. I do know there's been a bit of confusion around that so anything that improves that is welcome, although a change like this would be a breaking change, I'd have no problem with that.

**Comment by digia** [comment]
I hear you on the confusion - did quite a bit of double checking before bringing the issue up!

According to the draft it's suppose to be in seconds. Also i'm finding most libraries are using the seconds - surprised more haven't ran into an issue actually.

However with that all said it is a breaking change! 

I'll get a PR together and send it over.

**Comment by erichaus** [comment]
originally it was set up to support either seconds or milliseconds depending on what the backend server used...

**Comment by jpadilla** [comment]
@erichonkanen any specific reasons on why the default implementation is in milliseconds?

**Comment by erichaus** [comment]
To be honest no... it probably should have defaulted to seconds but I wasn't sure if e.g. node backends use seconds like python does

**Comment by jpadilla** [comment]
@digia let me know if you're still interested in putting a PR together for this

**Comment by digia** [comment]
@jpadilla Yes! Was waiting for the test issue to be sorted out.

Should be able to work on it later today!

**Comment by leo** [comment]
Fixed here: https://github.com/jpadilla/ember-simple-auth-token/pull/141

**Comment by digia** [comment]
Yes, fix pr is sent.

**Comment by jpadilla** [comment]
Closed by #141
