### ISSUE TITLE
Implement Options "refreshTokenAtRestore"

### ISSUE THREAD

**Issue by mako87** [fenichelar/ember-simple-auth-token#138]
it might be useful to implement an option that makes a token to restore refresh

if (wait > 0) {
          if (this.refreshAccessTokens) {
            this.scheduleAccessTokenRefresh(dataObject.get(this.tokenExpireName), token);
          }
          **if (this.refreshTokenAtRestore) {
            resolve(this.refreshAccessToken(token).then(() => { return data; }));
          } else {
            resolve(data);
          }**
        } else if (this.refreshAccessTokens) {
          resolve(this.refreshAccessToken(token).then(() => { return data; }));
        } else {
          reject(new Error('unable to refresh token'));
        }

**Comment by jpadilla** [comment]
This needs more information, closing for now.
