### ISSUE TITLE
Error: No authorizer was configured for Ember Simple Auth

### ISSUE THREAD

**Issue by nakardo** [fenichelar/ember-simple-auth-token#14]
I'm getting the following error on the console when starting up the App:

```
No authorizer was configured for Ember Simple Auth - specify one if backend requests need to be authorized.
```

My guess it that something has to be wrong with the configuration, so far I haven't find it. Here's what I have on my `index.html` (As shown on the docs):

``` html
  <body>
    <script>
      window.EmberENV = {{EMBER_ENV}};
    </script>
    <script src="assets/vendor.js"></script>
    <script src="assets/dashboard.js"></script>
    <script>
      window.DashboardNew = require('dashboard/app')['default'].create({{APP_CONFIG}});
    </script>
    <script>
      // https://github.com/jpadilla/ember-cli-simple-auth-token/issues/13
      window.ENV = window.ENV || {};
      window.ENV['simple-auth'] = {
        authorizer: 'authorizer:token',
        crossOriginWhitelist: ['http://localhost:3000']
      }
      window.ENV['simple-auth-token'] = {
        serverTokenEndpoint: 'http://localhost:3000/auth/sign-in'
      }
    </script>
  </body>
```

Any ideas?. Thanks!

**Comment by jpadilla** [comment]
@dmacosta  I've been working into refactoring this to use the new ember-cli's `ember addon` feature as well as adding tests.

I've created a new branch, [refactor](https://github.com/jpadilla/ember-cli-simple-auth-token/tree/refactor) with the current progress which seems to be working on an example project. All tests are passing.

I'd like some feedback on it and if you could try it out and report any weird things, that'd be awesome.

**Comment by nakardo** [comment]
Gracias Jose. So far it's working great for me on the new branch. Looking forward to see this published on the npm repo. I'll close the issue.
