### ISSUE TITLE
Request for source code of example site 

### ISSUE THREAD

**Issue by peavers** [fenichelar/ember-simple-auth-token#154]
I'm having issues getting this working, would you be able to upload the source code for the demo/example? Assuming you haven't already and I just can't find it... 

Regards,

**Comment by eluciano11** [comment]
Hi, you can find the demo app here:
https://github.com/jpadilla/ember-simple-auth-token/tree/master/tests/dummy

**Comment by peavers** [comment]
Ah, I knew it had to be somewhere. Thanks very much!
