### ISSUE TITLE
Acceptance Tests Timeout

### ISSUE THREAD

**Issue by albertosantiago** [fenichelar/ember-simple-auth-token#155]
Hi,

I have been doing some acceptance tests, and i had some problems with the jwt authenticator, your tests never finish, if you dont put in your testing environment:

ENV['ember-simple-auth-token']['refreshAccessTokens'] = false;

It's not a bug, but i spent some time in resolve that was the problem with my tests.... so maybe it will be useful for other.

Thanks for the plugin.

**Comment by acorncom** [comment]
Confirmed, I've run into this as well.  Do we want to update the docs to put in this info or would recommending that lead to other bugs?

**Comment by eluciano11** [comment]
Hi @acorncom @asantiago , thanks for pointing this out. I think we could add it to the docs until we find a solution for this bug. If you guys have a solution for this please feel free to make a PR. Let me know if you'd like to make a PR for the docs or if I should add it.

**Comment by acorncom** [comment]
I'll have time next Thursday, but if someone wants to beat me to it, that's fine on my end ;-)

**Comment by mongeta** [comment]
Can you share your acceptance test where you use the authenticateSession?

I can't pass any test in the protected area ... thanks

**Comment by jpadilla** [comment]
This might be fixed in master.
