### ISSUE TITLE
Allow Custom HTTP Methods

### ISSUE THREAD

**Issue by thegranddesign** [fenichelar/ember-simple-auth-token#158]
When dealing with the token, the REST-ful way of doing this would be to access the same resource with another HTTP method.

For example:

Getting a new token: `/sessions` <- via `POST`
Refreshing a token: `/sessions` <- via `PUT`, `PATCH` or a custom verb like `REFRESH`

Having two endpoints like `/getToken` and `/refreshToken` is RPC-style.

The way the code is currently written, both the normal and refresh endpoints use `POST`.

**Comment by thegranddesign** [comment]
BTW, I'd be willing to PR this.

**Comment by jpadilla** [comment]
Not immediately sure how'd this look and work. Definitely willing to look at a PR to further discuss.

**Comment by jpadilla** [comment]
Passing on this for now.
