### ISSUE TITLE
Support for Ember Data requests

### ISSUE THREAD

**Issue by PatrickFranken** [fenichelar/ember-simple-auth-token#16]
We're using Ember with Ember Data and all request from Ember Data do not containt the Authorization header.
Our research showed up two possible causes:
- Ember Data overwrittes the header settings
- Ember Data does not use jqXHR at all

Any ideas on this?

**Comment by jpadilla** [comment]
Ember Simple Auth should work with Ember Data. They have an [example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/5-ember-data.html) which might help.

**Comment by PatrickFranken** [comment]
So actual problem is, that in no case the authenticatin header is delivered. I really have no idea why. The API adress is already white listed. So it should probably work.
Is there any information what I could deliver?
