### ISSUE TITLE
acceptance test failing

### ISSUE THREAD

**Issue by julianrubisch** [fenichelar/ember-simple-auth-token#163]
I'm not quite sure how to go about acceptance testing using the JWT authorizer, maybe you could advise?

My acceptance test is set up thusly:

```
import Ember from 'ember';
import { module, test } from 'qunit';
import moduleForAcceptance from 'myapp/tests/helpers/module-for-acceptance';
import startApp from 'myapp/tests/helpers/start-app';

import { currentSession, authenticateSession, invalidateSession } from 'myapp/tests/helpers/ember-simple-auth';

moduleForAcceptance('Acceptance | login', {
  beforeEach: function() {
    this.application = startApp();
  },

  afterEach: function() {
    Ember.run(this.application, 'destroy');
  }
});

test('validate the session', function (assert) {

    authenticateSession(this.application);

    visit('/clients');

    andThen(function () {
        assert.equal(currentURL(), '/clients');
    });

});
```

However, the assertion fails, and in the browser dev tools I see that I get a 401 Response on the client route ('bad credentials'). I was simply following this gist: https://gist.github.com/ryanlabouve/c86bcfd1956a04d6d4f0c226528ce44b

Ember 2.5.0, ember-cli 1.13.8, ESA 1.0.1, ember-simple-auth-token 1.1.1

Thanks!

**Comment by mongeta** [comment]
I'm having more or less the same problem, always getting the 401.

For the docs, we need to pass additional info for the token in the authenticateSession:

`authenticateSession(app, sessionData): authenticates the session; the optional sessionData argument can be used to mock an authenticator response - e.g. a token.`

But I'm adding the token response (sure I'm doing it wrong) with no success ...

thanks

**Comment by jpadilla** [comment]
This might be fixed in master.
