### ISSUE TITLE
Cant get my headers to work with JWT

### ISSUE THREAD

**Issue by MarjovanLier** [fenichelar/ember-simple-auth-token#164]
Hi guys I have tried allot of exmples and read through as much as I can, but I cant the the refresh headers to send. Can you please help me?

packages.json
`....
    "ember-simple-auth": "1.1.0",
    "ember-simple-auth-token": "1.1.1",
....`

adapters/application.js:

` 
import DS from 'ember-data';
import ENV from '../config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin,{
    namespace:'api',
    authorizer: 'authorizer:jwt'
});
`

config/environment.js
`    ENV['ember-simple-auth'] = {
        authorizer: 'authorizer:jwt',
    };

```
ENV['ember-simple-auth-token'] = {
    identificationField: 'email',
    passwordField: 'password',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'Authorization',
    refreshAccessTokens: true,
    refreshLeeway: 115,
    timeFactor: 1000,

    serverTokenEndpoint: ENV.apiBaseUrl + '/api/v1/user/auth/login',
    serverTokenRefreshEndpoint: ENV.apiBaseUrl + '/api/v1/user/auth/refresh',
};`
```

controllers/login.js
`import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticate: function() {
      var credentials = this.getProperties('identification', 'password'),
        authenticator = 'authenticator:jwt';

```
  this.get('session').authenticate(authenticator, credentials)
  .then(() => {
    this.transitionToRoute('test');
  })
  .catch((message) => {
    this.set('errorMessage', message.error || message);
  });
}
```

  }
});`

**Comment by MarjovanLier** [comment]
I am new to laravel. Maybe i have some config issue, but I finally got the Authorization headers to send. I had to update the node package, there must be a way to overwrite this function.

This is the change i made to jwt.js:

`makeRequest(url, data, headers) {
    const token = Ember.get(data, this.tokenPropertyName);
    return Ember.$.ajax({
      url: url,
      method: 'POST',
      data: JSON.stringify(data),
      dataType: 'json',
      contentType: 'application/json',
      headers: this.headers,
      beforeSend: (xhr, settings) => {
        xhr.setRequestHeader('Accept', settings.accepts.json);
        if (!Ember.isEmpty(token)) {
          xhr.setRequestHeader('Authorization', 'Bearer '+ token);
        }
        if (headers) {
          Object.keys(headers).forEach(key => {
            xhr.setRequestHeader(key, headers[key]);
          });
        }
      }
    });
  },`

**Comment by costinbogdan** [comment]
hi everyone, are you working with ember and laravel?
Can you help me please. I have an error in js "http://localhost:4200/api/token-auth/ 404 (Not Found)". Can you help me?
