### ISSUE TITLE
Manually authenticating with token

### ISSUE THREAD

**Issue by DiederikvandenB** [fenichelar/ember-simple-auth-token#165]
Hi all,

First of all, thanks for making and maintaining this repo :). However, there is one thing I can't seem to figure out. On the project I am working on, we don't get to authenticate the users ourselves. What happens is this:

User presses login -> goes to a third party authenticator -> a request is sent to our API -> our API generates a JWT token for the user -> the user is returned to the ember application with a JWT token.

All I have to do now is somehow authenticating the user in Ember by just saving the JWT token somewhere. How :)?

**Comment by crhayes** [comment]
I am currently doing the same thing.

The action that handles signing in looks like this:

``` js
actions: {
    signin() {
      const slug = this.get('controller.model.slug');

      this.get('session').authenticate('authenticator:torii', 'google', slug);
    },
  },
```

Note that I am using the torii authenticator, with the google provider, and also passing in a slug; the slug is required by my custom backend authentication mechanism (that provides me a JWT token).

I extended the `ToriiAuthenticator` `authenticate` method to look like this:

``` js
export default ToriiAuthenticator.extend({
  torii: Ember.inject.service(),
  auth: Ember.inject.service(),

  authenticate(provider, ...args) {
    return this._super(...arguments).then(data => {
      return this.get('auth').authenticate(...args, data.authorizationCode);
    }).then(res => { 
      provider, 
      access_token: res.token
    });
  }
});
```

What is happening is:
1) I immediately defer to `this._super`, which performs the normal Torii authentication 
2) I chain a `.then` which accepts the data resulting from the authentication; this includes the authorization code (in this case from Google)
3) I use my custom `auth` service and call it's `authenticate` method. Note that I pass it `...args` (this includes the additional data I authenticated with - in this case the `slug`) and the authorizeCode. This method returns a promise
4) I chain another `.then` which is called after my custom `authenticate` method resolves; Whatever I return from here is what will be stored as the "session state" (in this case it gets stored in local storage). I return the provider and the access token I received in the response from my server.

I hope that helps anyone with the same issue!

**Comment by gzurbach** [comment]
Thanks @crhayes that totally works! I am adding below a version of the code using the token authenticator in case anyone needs it. It's dead simple!

```js
import TokenAuthenticator from 'ember-simple-auth-token/authenticators/token';

export default TokenAuthenticator.extend({
  authenticate(token) {
    return new Promise((resolve, reject) => {
      if (token) {
        return resolve({ token });
      } else {
        reject(new Error('Token not provided.'));
      }
    });
  }
});
```

See https://github.com/simplabs/ember-simple-auth#implementing-a-custom-authenticator for more details.
