### ISSUE TITLE
identificationField can't overwrite 

### ISSUE THREAD

**Issue by herzzanu** [fenichelar/ember-simple-auth-token#170]
Trying to use `email` instead of the default `identification` with `identificationField: 'email'` but it's not working. It only works if I use `identification` in my login form. Any ideas?

**Comment by Eusse** [comment]
I'm getting the same issue with the password also. I think i know what the problem is. I will PR if i find the solution.

**Comment by gogromat** [comment]
+1. Can this be merged into 1.2.1?
