### ISSUE TITLE
Session isAuthenticated true for expired tokens

### ISSUE THREAD

**Issue by hirecom** [fenichelar/ember-simple-auth-token#174]
After logging in, it shows that session isAuthenticated is true.  However, when a token has expired, it's still showing isAuthenticated as true.  Only invalidating the session turns it to false.  Anyone else seeing this?

**Comment by jeremyguarini** [comment]
Yes I see it too. Was looking for some config I missed when I found this post. Does anyone have a code sample to show how to invalidate the session automatically when the token expires?

thanks

**Comment by evoactivity** [comment]
I think I'm seeing this as well. I can load my authenticated route just fine with an expired token, my api requests are rejected though because the token is no longer valid.

edit: It seems you'll never be unauthorised if you don't have refreshAccessTokens set to true

**Comment by jeremyguarini** [comment]
Hi,

Anyone figure out how to get the token invalidated when it expires? My current experience is that I get a new session, close the browser, open it after the expiration and the last route kind of loads. It's not until I click on a different route that it seems the token is evaluated and invalidated. What would be nice is when re-opening the browser the token is checked when the page loads up and the user is directed to the login page (or some other appropiate action).

thanks

**Comment by jeremyguarini** [comment]
So taking a look at my current set-up I was able to get sessions to redirect to login on page load by updating my app/index/controller.js with the following:

` session: Ember.inject.service('session'),
  setSessionClaims: Ember.observer('session.data.authenticated.token', function() {
    if (this.get('session.data.authenticated.claims.exp') < Math.floor((new Date).getTime()/1000)) {
      return this.get('session').invalidate();
    }
      if(this.get('session.data.authenticated.token')) {
          try {
            var claims = JSON.parse(atob(this.get('session.data.authenticated.token').split('.')[1]));
            this.set('session.data.authenticated.claims', claims);
          } catch (error) {
              return alert('Failed to JSON.parse(claims) '+error);
          }
      }
  }).on('init'),`

not totally sure how decent of a hack this is, but it appears to be working so far.

thoughts?

**Comment by jembezmamy** [comment]
It seems I'm experiencing something similar - sometimes token refresh request is not performed (not  sure why, but I think it doesn't matter) and then I'd expect session to get invalidated, but it doesn't happen. This is bad, because users can still perform some signed-in-only actions, but server rejects their changes.

**Comment by jpadilla** [comment]
This should be fixed in master.
