### ISSUE TITLE
Publish latest with #150 and #160

### ISSUE THREAD

**Issue by knownasilya** [fenichelar/ember-simple-auth-token#176]
Would love it if you could publish a new version.

**Comment by jpadilla** [comment]
@knownasilya still haven't pulled the trigger on another release because master branch seems to be failing for some reason. I haven't been able to check that out. Any help with that would be awesome.

**Comment by kris-ellery** [comment]
Fixed in https://github.com/jpadilla/ember-simple-auth-token/pull/177.

**Comment by jpadilla** [comment]
v1.2.0 is out! Thanks again everyone. Always on the look out for anyone with a few cycles to help maintain this package.
