### ISSUE TITLE
undefined sessionData for authenticate resolve with JWT authenticator

### ISSUE THREAD

**Issue by mblayman** [fenichelar/ember-simple-auth-token#180]
My goal is to get the token data after a successful authentication so I can extract a user ID and query my API to get more user information. My login controller has code that looks like:

```js
this.get('session').authenticate('authenticator:jwt', credentials).then(
  (sessionData) => {
     console.log(sessionData); // Logs "undefined"
  },
  (reason) => {
    // not important for this issue
  });
```

I found this confusing because the authenticator passes `sessionData` to the resolve callback. To be sure, I tossed in a couple of `console.log` statements.

```js
      this.makeRequest(this.serverTokenEndpoint, data, headers).then(response => {
        Ember.run(() => {
          try {
            const sessionData = this.handleAuthResponse(response);
            console.log(sessionData);
            console.log(this.getTokenData(sessionData.token));

            resolve(sessionData);
          } catch(error) {
            reject(error);
          }
        });
```

In Chrome, these log statements produced:

![image](https://cloud.githubusercontent.com/assets/636865/21212780/c40fecf0-c25d-11e6-9e48-58c09e53d561.png)

Perhaps I have a misunderstanding of the Ember run loop (or promises), but I assumed that the `sessionData` in the authenticator code would be the same as the `sessionData` in my resolve callback.

Any idea what's going on here? Is there another way possible to get access to the token data for the currently authenticated user? Thanks!

**Comment by mblayman** [comment]
Shoot, sorry for the noise. I should have Googled it before wasting all this time writing an issue. `authenticate` is an `ember-simple-auth` API and it doesn't resolve with a value. Looks like the data is accessible via the session's `authenticated` property.

**Comment by zomarg** [comment]
I have a question why is ember-simple-auth-token not returning the decoded token data?
There are many use cases when you want to use the claims directly from session.data.authenticated.

**Comment by mblayman** [comment]
@GramozKrasniqi I think part of the problem is out of `ember-simple-auth-token`'s hands. `ember-simple-auth` is what controls the return value of the authenticate promise. To deal with this, I imported the JWT authenticator into my app and called its `getTokenData` method. For me, that ended up looking like this:

```javascript
import Ember from 'ember';
import JWT from 'ember-simple-auth-token/authenticators/jwt';

const { inject: { service }, isEmpty, RSVP } = Ember;

export default Ember.Service.extend({
  session: service(),
  store: service(),

  load() {
    return new RSVP.Promise((resolve, reject) => {
      const token = this.get('session.data.authenticated.token');
      if (!isEmpty(token)) {
        const userId = this.getUserIdFromToken(token);
        this.get('store').find('user', userId).then((user) => {
          this.set('user', user);
          resolve();
        }, reject);
      } else {
        resolve();
      }
    });
  },

  getUserIdFromToken(token) {
    const jwt = new JWT();
    const tokenData = jwt.getTokenData(token);
    return tokenData['user_id'];
  }
});
```

**Comment by zomarg** [comment]
@mblayman yep this would be a solution, but the problem is that you wont be using only jwt authenticator and in that case it will fail (minght be that you have another encoding or it is encoded).

I changed the jwt implementation a bit and it seems that the changes are working thats why i asked if there were any reason why the jwt implementation is not returning the decoded token.

This is the code from the original jwt authenticator handleAuthResponse method.

'handleAuthResponse(response) {
    const token = Ember.get(response, this.tokenPropertyName);

    if (Ember.isEmpty(token)) {
      throw new Error('Token is empty. Please check your backend response.');
    }

    const tokenData = this.getTokenData(token);
    const expiresAt = Ember.get(tokenData, this.tokenExpireName);
    const tokenExpireData = {};

    tokenExpireData[this.tokenExpireName] = expiresAt;

    this.scheduleAccessTokenRefresh(expiresAt, token);

    return assign(this.getResponseData(response), tokenExpireData);
  },`

I changed the last line to

`return tokenData;`

and now i have the decoded token into the store. 

P.S i am trying to find out if this solution creates any side effects.

**Comment by mblayman** [comment]
Good points. 😄 I'm not sure of original author's intent here so it's an interesting suggestion. As someone else who would benefit from having the decoded data returned, I would love to know the reason too.

**Comment by zomarg** [comment]
@mblayman  please dont use `return tokenData;` 
instead use `return assign(this.getResponseData(response), tokenData);`
The first one dosent send the authorization header :D.
