### ISSUE TITLE
Token not sent on API calls 

### ISSUE THREAD

**Issue by rymoore** [fenichelar/ember-simple-auth-token#185]
I have a JWT token working great on login / page requests, but it is not working on API calls. Here is what I have set up:

_adapters/application.js_
```
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.RESTAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:jwt'
```

_config/environment.js_
   ```
 "ember-simple-auth": {
      authorizer: 'authorizer:jwt'
    },

    'ember-simple-auth-token': {
    ...
    }
```

When I inspect my XHR GET requests, there is no token being passed. What might I be doing wrong?

I'm using:
    "ember-simple-auth": "1.2.0-beta.1",
    "ember-simple-auth-token": "2.0.0", 

Would it have anything to do with the 1.2 beta?

**Comment by ReekenX** [comment]
Please check if your authorization response (the one which you are making with `authenticate`) is returning back you `token` key.

If it's not returning anything like that by json after authorization - it is not saved so future API calls are without your token.

**Comment by rymoore** [comment]
Yes, I can see the key being stored in Local Storage

**Comment by rymoore** [comment]
Anything else I can do to debug / test this @ReekenX ?

**Comment by ReekenX** [comment]
I do not have any ideas except debugging code of ember-simple-auth-token.

**Comment by amk221** [comment]
Might be completely unrelated, but maybe you could try what I did [here](https://github.com/jpadilla/ember-simple-auth-token/issues/175#issuecomment-273247577).

**Comment by rymoore** [comment]
I am getting this warning, might it have anything to do with it?

_ember.debug.js:6628DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]_

**Comment by rymoore** [comment]
The issue seems to be because `authorizer` is null on this line in ember-simple-auth/services/session

 ```
authorize: function authorize(authorizerFactory, block) {
      if (this.get('isAuthenticated')) {
        **var authorizer = (0, _emberGetownerPolyfill['default'])(this).lookup(authorizerFactory);**
        var sessionData = this.get('data.authenticated');
        authorizer.authorize(sessionData, block);
      }
```

however, I do have it defined in /adapters/application.js

```
export default DS.RESTAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:jwt'
```

**Comment by rymoore** [comment]
If I change my authorizer to 'token' it seems to work. 

  `authorizer: 'authorizer:token'`

this does not jive with the repo documentation however, which says:

`authorizer: 'authorizer:token' //or authorizer: 'authorizer:jwt'`

**Comment by amk221** [comment]
Looks like a duplicate issue then

**Comment by rymoore** [comment]
Yeah... but I'm not actually able to make this work. When I make the switch to 'token', I now get 

_TypeError: Cannot read property 'authenticate' of undefined_

**Comment by rymoore** [comment]
Can anyone confirm if someone has _ever_ successfully gotten JWT auth to work? Trying to figure out if this is just something wrong with my project or if this library isn't ready.

**Comment by eluciano11** [comment]
Hello @rymoore sorry for the late response. The addon is currently working but the docs are incorrect. Specifying `authorizer:token` works fine and specify the jwt fields in your `ember-simple-auth-token` object. 

Updating the docs to avoid other issues like this.

Thanks for reporting this issue, sorry for the inconvenience.

**Comment by eluciano11** [comment]
Updated the docs.
