### ISSUE TITLE
Custom payload for JSON authentication.

### ISSUE THREAD

**Issue by ghost** [fenichelar/ember-simple-auth-token#186]
I need to know how to modify JSON payload sent to the server without write a custom authenticator in `authenticators` folder?

For example this is what I have now, with default:

`{"identification":"myUsername","password":"myPassword"}`

Now I need something like this:

`{"auth": {"identification":"myUsername","password":"myPassword"}}`

Maybe in `controllers/login.js` in `authenticate()` action?

I'm afraid of write buggy code myself in a custom `authenticators/auth.js` file.

I thought something like this: 

```
authenticate(credentials) {
    const myJSON = JSON.stringify({
      auth: {
        email: credentials.email,
        password: credentials.password
      }
    });
```

but where and when?

**Comment by Subtletree** [comment]
You're really close by the looks of things. Instead of overwriting `authenticate` you could overwrite the `getAuthenticateData` method.

Make a new file called `authenticators/jwt.js`:
```
import Jwt from 'ember-simple-auth-token/authenticators/jwt';

export default Jwt.extend({
  getAuthenticateData(credentials) {
    const authentication = {
      auth: {
        [this.passwordField]: credentials.password,
        [this.identificationField]: credentials.identification
      }
    };

    return authentication;
  }
}
```

If you're not using jwt then replace everything that says `jwt` with `token`
