### ISSUE TITLE
Authorizer trying to get token at the wrong place

### ISSUE THREAD

**Issue by acamaral** [fenichelar/ember-simple-auth-token#191]
Hi guys,

I'm using:

ember-simple-auth - **1.2.0**
ember-simple-auth-token - **2.1.0**

In file **_authorizer/token.js_**, function **_authorize()_**, you try to get **_token_** accessing **_data.token_**, but it is not there. It's at **_data.data.attributes.token_**.

Hope this tip help you to make this addon even better.

**Comment by jpadilla** [comment]
@acaxon you should be able to set the `tokenPropertyName` [setting](https://github.com/jpadilla/ember-simple-auth-token#available-customization-options) to `data.attributes.token`.
