### ISSUE TITLE
Question about sending token

### ISSUE THREAD

**Issue by MtthwBrwng** [fenichelar/ember-simple-auth-token#192]
Hello,

I have a feeling I'm doing something wrong but currently I am sending the token as a json response. I'm not sure if I'm suppose to be doing something else but at the current state it the request is made to the backend server and it returns a token and the Ember app does nothing. If anyone could help that would be great. Thanks.

**Comment by alechirsch** [comment]
@MattJBrowning Have you figured out what was going wrong? Can this be closed?

**Comment by MtthwBrwng** [comment]
Yes, this was resolved.
