### ISSUE TITLE
Custom headers are not being sent

### ISSUE THREAD

**Issue by poohitan** [fenichelar/ember-simple-auth-token#194]
I've added a custom `Content-Type` header in my plugin config. The problem is that this header is not being sent when I do the `/authenticate` request. `text/plain` is sent instead of `application/vnd.api+json`.

I encountered this bug on Firefox 43.0.1 (Windows 10) and it disappeared after I've updated to Firefox 47.

Here is my ember-simple-auth-token config:
```javascript
  ENV['ember-simple-auth-token'] = {
    serverTokenEndpoint: `${ENV.apiURL}/authenticate`,

    identificationField: 'email',
    passwordField: 'password',

    headers: {
      'Content-Type': 'application/vnd.api+json'
    }
  };
```

**Comment by jherdman** [comment]
Is this documented behaviour for e-simple-auth? I'm having trouble tracking this down. My understanding is that you're supposed to pass in customer headers to the authenticator. Example:

```javascript
const headers = {
  'Accept': 'application/vnd.api+json',
  'Content-Type': 'application/vnd.api+json',
};

this.get('session').authenticate('authenticator:token', credentials, headers);
```

**Comment by scottkidder** [comment]
Why was this closed?

I used to be able to pass dynamic headers to
`this.session.authenticate('authenticator:custom', credentials, headers)`

but this appears to be longer supported. The authenticator now always makes the request with headers from configuration.
https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/token.js#L67

Previously working:
https://github.com/jpadilla/ember-simple-auth-token/blob/027ad00e836998ae623f5929e0480745a3339115/addon/authenticators/token.js#L126

Is there a reason this was removed or can it be added back? Happy to make a PR.

**Comment by fenichelar** [comment]
@scottkidder PR incoming.

**Comment by fenichelar** [comment]
I did not test it yet, but I think that will address the issue.

Edit: Unit tests added. I think this should address the issue. The headers from the configuration are always sent but they can be overwritten and new headers can be added dynamically the same way as before `authenticate(credentials, headers)`.

**Comment by scottkidder** [comment]
Yup that looks great. Thanks @fenichelar. :dash:

**Comment by fenichelar** [comment]
`merge` permanently changes the `this.headers` value. Need to fix.

Edit: Fixed.

**Comment by fenichelar** [comment]
Travis is happy. I think it makes sense to release v4.0.2 to address this issue if @jpadilla agrees?
