### ISSUE TITLE
Confusion Around Refresh Token (Missing Authorization Header)

### ISSUE THREAD

**Issue by adam820** [fenichelar/ember-simple-auth-token#198]
Hello! After working through #197 and getting the package updated, I'm still running into an issue regarding refresh tokens that I'm starting to think is a mismatch between what my API backend expects and what is the expected behavior of ESAT.

With my current setup, both GETs and POSTs to the API are including the Authorization header with the access token (so far, so good). However, when the refresh period rolls around, there's a POST to my `/auth/refresh` endpoint that contains the refresh token in the body, but with no Authorization header. Conversely, the API (flask-restplus & flask-jwt-extended) appears to want a POST with no payload, but with the refresh token in the Authorization header. Whenever I do this procedure manually with Postman, I get the correct results, however when ESAT does the POST it rejects it as missing the Authorization header.

I tried building a small application from scratch implementing auth and ran into the same issue, so it seems it's client-side.

Does this sound like the expected behavior from ESATs end? I think I may not need to rely on the API's built-in refresh verification and build my own based on ESAT's behavior if this is correct.

```
  ENV['ember-simple-auth-token'] = {
    serverTokenEndpoint: ENV.REST_HOST + '/auth',
    identificationField: 'username',
    passwordField: 'password',
    tokenPropertyName: 'access_token',
    refreshTokenPropertyName: 'refresh_token',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'Authorization',
    headers: {},

    //JWT-specific options
    refreshAccessTokens: true,
    serverTokenRefreshEndpoint: ENV.REST_HOST + '/auth/refresh',
    tokenExpireName: 'exp',
    //Set short for testing.
    refreshLeeway: 50
  };
```

Request headers (Authorization missing):
```
POST /auth/refresh HTTP/1.1
Host: 0.0.0.0:5000
Connection: keep-alive
Content-Length: 291
Accept: application/json, text/javascript
Origin: http://localhost:4200
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Content-Type: application/json
DNT: 1
Referer: http://localhost:4200/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8

```

**Comment by adam820** [comment]
Assuming this is expected behavior, I ended up writing my own handler on the API side for having the refresh token in the payload vs. header. For anyone else who may be searching this out, though, I'd be interested to know for sure.

**Comment by alechirsch** [comment]
@adam820 The expected behavior is to have the refresh token sent in the payload of the request rather than in the header. I am closing this issue for now.

**Comment by tarponjargon** [comment]
@adam820 I am using flask-jwt-extended and just noticed the exact same issue. Could you share the specifics of your workaround?

**Comment by tarponjargon** [comment]
Nevermind - I think I got it.  Here's my solution in case somebody else needs it:

https://gist.github.com/midget2000x/8924fae4cca98a0a70884612c5f9e6d3

**Comment by adam820** [comment]
@midget2000x Sorry for not getting back to you sooner; a quick look at what you did basically looks like a more elegant version of what I ended up doing. Mine wasn't done as a decorator.

**Comment by 0xecute** [comment]
@tarponjargon The link is not working anymore. Can you paste the code please?

**Comment by fenichelar** [comment]
@0xecute 

You could create `app/authenticators/jwt.js` with the following:

```js
import { merge } from '@ember/polyfills';
import JWT from 'ember-simple-auth-token/authenticators/jwt';

export default JWT.extend({
  refreshAccessToken(token) {
    return new Promise((resolve, reject) => {
      const headers = merge(this.headers, {
        'Authorization': `Bearer ${token}`,
      });
      this.makeRequest(this.serverTokenRefreshEndpoint, {}, headers).then(response => {
        try {
          const sessionData = this.handleAuthResponse(response.json);
          this.trigger('sessionDataUpdated', sessionData);
          return resolve(sessionData);
        } catch (error) {
          return reject(error);
        }
      }).catch(error => {
        this.handleTokenRefreshFail(error.status);
        return reject(error);
      });
    });
  },
});
```
