### ISSUE TITLE
Tag 2.1.0 is behind master for refreshTokenPropertyName options on JWT

### ISSUE THREAD

**Issue by stannok** [fenichelar/ember-simple-auth-token#201]
Is seems that the Tag 2.1.0 is behind the master branch.

Please see:
https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/configuration.js
https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/jwt.js

The missing code is in relation to the setting of a custom refreshTokenPropertyName, which is missing in tagged release.

**Quick Fix**:
Anyone experiencing this issue could copy the correct code from above links when using npm (no install from master possible). At least until a new release is tagged from master branch.

**Comment by jpadilla** [comment]
@stannok thanks for the heads up. I'll get to it sometime this week.

**Comment by MarSik** [comment]
I also hit this. This basically prevents using separate access and refresh tokens.
