### ISSUE TITLE
Restore session when refresh browser

### ISSUE THREAD

**Issue by ChangJoo-Park** [fenichelar/ember-simple-auth-token#203]
Hello I am using Rails 5 with ember.js
Backend using [devise token auth](https://github.com/lynndylanhurley/devise_token_auth)

I use authenticator **"authenticator:token", but everytime I refresh browser, ember.js console said to me 

**The authenticator "authenticator:token" rejected to restore the session - invalidating…**

How do I restore session when I refresh browser?

below my repo for reporting.
https://github.com/ChangJoo-Park/esat-reporting

**Comment by ChangJoo-Park** [comment]
I think ember_simple_auth-session did not have token property.

**Comment by snewcomer** [comment]
@ChangJoo-Park I'm wondering the same thing as well in development (using mirage).  I'm sure somebody has figured this out :microphone: ??

**Comment by stephanebruckert** [comment]
@ChangJoo-Park any chance you figured that one out?

**Comment by jpadilla** [comment]
This might be fixed in master.
