### ISSUE TITLE
Refresh Token Support

### ISSUE THREAD

**Issue by kcaulfield94** [fenichelar/ember-simple-auth-token#211]
So there is a mismatch when installing via npm and when using the direct github link. Via npm, the plugin will try to hit my refresh endpoint but sends the regular token, not the refresh token. This is not the case with a direct install.

Any plan or timeline for getting this up to date in the registry?

Thanks!

**Comment by dcyriller** [comment]
Hello @jpadilla, thanks for your work on this addon, it is very usefull. I just ran into the same issue described by @kcaulfield94 

Would you mind releasing a new version on npm ? (containaing especially [this commit](https://github.com/jpadilla/ember-simple-auth-token/commit/c34e3e91e68ac3d5847789f05c3ecc18f5ab030a))

I can just use master, but using a tagged version would make me feel better. :)

**Comment by kcaulfield94** [comment]
Just checking back in for any sort of progress. Is this still maintained @jpadilla ?

Again, thanks!

**Comment by jpadilla** [comment]
Yeah I was hoping to get some time to bring everything up to date before release v3 with #190. Unfortunately I don't think I'll have time to do it soon. Anyone else want to help with that? If not I'll release v3 as is in upcoming days.

**Comment by kcaulfield94** [comment]
Are there any pressing issues that would result from releasing v3 as is?

**Comment by kcaulfield94** [comment]
Also, thanks for the response :) EDIT: after looking at #190 I realize what you're saying. What I am looking for specifically is the separate refresh token when I install from npm.

**Comment by dcyriller** [comment]
@jpadilla I did a PR to update ESA + ember-{cli,source} versions here: #212 wdyt ?

**Comment by kcaulfield94** [comment]
Much Appreciated @dcyriller

**Comment by kcaulfield94** [comment]
@dcyriller @jpadilla I saw that this was merged, did this include support for the separate refresh_token? Looks that way?

**Comment by jpadilla** [comment]
@kcaulfield94 yeah it will, I'm revisiting @knownasilya's last comment https://github.com/jpadilla/ember-simple-auth-token/pull/190#issuecomment-302432273 now.

**Comment by jpadilla** [comment]
Thank you all again! Just released [v3.0.0](https://github.com/jpadilla/ember-simple-auth-token/releases/tag/v3.0.0) 🎉

**Comment by dcyriller** [comment]
Thank you @jpadilla !
