### ISSUE TITLE
Use token properties in Ember client

### ISSUE THREAD

**Issue by objectiveSee** [fenichelar/ember-simple-auth-token#215]
Hello! We are looking for a way hide/show certain features in our Ember app based on the user's `role` at the company. Currently, we are using `ember-simple-auth-token` and our API server will validate the login (via Google Auth) and then respond back with a JWT token. I am curious, would it be a wise practice to include the `role` of the user within the JWT token? Is it possible for the Ember client to access properties within the JWT token? If not, how would you recommend we tell the client what the user's `role` is?

**Comment by NerijusD** [comment]
Actually yes. That would be a smart thing to do, you can add custom fields in your JWT and anyone can read it, however the strength of JWT is that you can NOT alter it unless you know secret key.

I encourage you to play around with this builder: http://jwtbuilder.jamiekurtz.com/

Try this JWT: 
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE1MTY5MDQ5ODgsImV4cCI6MTU0ODQ0MDk4OCwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIlJvbGUiOiJBZG1pbiJ9.d_dQ-scdMxsNS3Qa2WkWr2JTVwQIAlAimsfRYim5KqE

you can decode without secret key and see the value of custom field "Role".

![image](https://user-images.githubusercontent.com/14087140/35405493-99321636-0206-11e8-9267-c27874952bd1.png)

**Comment by charlesfries** [comment]
For anyone looking to decode tokens client side in the future, it's super easy to do:

```
let [header, payload] = token.split('.');

header = JSON.parse(atob(header));
payload = JSON.parse(atob(payload));
```
