### ISSUE TITLE
Session lost on page refresh

### ISSUE THREAD

**Issue by erichaus** [fenichelar/ember-simple-auth-token#22]
Hello,

I'm noticing an issue where if I do a hard refresh of a page in my Ember app, the custom session appears to be lost. I'm not sure if this is something related to this package or not because the refresh does keep me logged in without redirecting to login page. 

Error while processing route: organizations.index Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined

Here is my code where I create custom session, am I doing that correctly? I'm still new to Ember/Dependency injection etc...

https://github.com/erichonkanen/cl-frontend/blob/master/app/initializers/session.coffee

and here is my temp code for getting the session.user in a route:

https://github.com/erichonkanen/cl-frontend/blob/master/app/routes/organizations/index.coffee#L6

Also, where is the session stored? In my localstorage I notice "ember_simple_auth:token" which has just the token stored.. Should it be storing the custom session w/user object in it?

Any help appreciated!!

Thanks
(PS my goal is to be able to have access to the session.user from both templates (working) and routes (not working after refresh)

**Comment by jpadilla** [comment]
@erichonkanen does this also happen when you're not using a custom session?

**Comment by jpadilla** [comment]
@erichonkanen not really sure why the session is being "lost" here. I just tried something similar, except I'm not doing a lookup on the container for the model object.

My guess it might be something with the data that is stored on localstorage. When you refresh I think the `authenticator.restore()` function is called, if there is no key that matches whatever is set on `authenticator.tokenPropertyName` (by default it's `token`) it will return a rejected promise, which is what is probably logging you out. Not really sure what else it could be.

The session is stored by default in the localstorage. What's the value for "ember_simple_auth:token"? It should be something like:

``` json
{"authenticator":"simple-auth-authenticator:token","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidXNlcl9pZCI6MSwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsImV4cCI6MTQyMDIyOTYzNH0.STwwfUzXEyA9pz8UG6Nsaafm-v6s-OP6P7AzGedQi8Y"}
```

Whatever you're doing on your custom session will not be stored in the storage.

Other than that, I'm not 100% sure this is an issue with this package.

**Comment by erichaus** [comment]
@jpadilla that is exactly what my "ember_simple_auth:token" looks like.. I think whats happening is like you said, the custom session data isn't persisted so if I refresh the page, although it has the "ember_simple_auth:token" stored and thus it can load/log into the page, it doesnt have the User that I add in the custom session. I think then what happens is it will load the route and thus the model and then it makes a query but w/o the custom session data (user context) I use in a query param for the model which filters the returned data in relation to the context supplied.

So example:
   Without refresh: app.com/organizations/ -> GET /api/v1/organizations?context=3
   With hard refresh: app.com/organizations/ -> GET /api/v1/organizations?context=

http://imgur.com/a/h8dFE

It seems that the page that loads doesnt have the custom data bc the 1st call is the route being loaded and then 2nd call grabs the User data... If I navigate to a different page and the next page has the context set on the session.. I'm not sure if theres a way to force it to first grab the User data/session data before loading the route?

**Comment by jpadilla** [comment]
@erichonkanen btw don't know if it makes a difference, but you might also try doing `@get 'session.context'` instead of `@session.context`.

**Comment by pentagon** [comment]
Another case when the session gets lost:
- server side response with object like: `{user: {token: 'xxx'}`
- env config contains the following:

```
ENV['simple-auth-token'] = {
   ....
    tokenPropertyName: 'user.token',
  };
```

authenticator/token.js restore(..) method doesn't expect tokenPropertyName configured like given above.

**Comment by jpadilla** [comment]
@pentagon mind opening an issue on just that? Perhaps a failing test case as well. If you're up to it an PR with a fix would be even better!

**Comment by pentagon** [comment]
@jpadilla sure, i'll come up with PR soon
