### ISSUE TITLE
Token not being sent in AJAX requests

### ISSUE THREAD

**Issue by jzcorrea** [fenichelar/ember-simple-auth-token#220]
Hi guys,

I recently updated my Ember app from Ember 1.13.13 to Ember 2.18.2, with `ember-simple-auth@1.6.0` and `ember-simple-auth-token@3.0.0`. I use JWT for authentication.

My app does not use Ember Data & Ember Data models. We have a lib called `api.js` that makes AJAX requests to our API. This is a sample of the implementation of the call:

```js
// api.js
return $.ajax({
   url: `${API_ENDPOINT}${url}`,
   type: method, // POST, GET, PUT, DELETE
   contentType: 'application/json',
   dataType: 'json',
   data: JSON.stringify(params),
   xhr() {
	const xhr = $.ajaxSettings.xhr();
	// [...] Some code for upload requests
	return xhr;
   }
})
```
Note: This lib is just an object with some methods imported in routes, controllers, etc. It is not an Ember service or something like (one of the next steps after the migration to Ember 2.18.2 is transform this lib into a service).

`ember-simple-auth` and `ember-simple-auth-token` configuration in `environment.js`:

```js
{
        'ember-simple-auth': {
		store: 'session-store:local-storage',
		authorizer: 'authorizer:token',
		crossOriginWhitelist: ['*']
	},
	'ember-simple-auth-token': {
		refreshAccessTokens: true,
		timeFactor: 1000,
		tokenPropertyName: 'token',
		refreshTokenPropertyName: 'token',
		refreshLeeway: 300,
		tokenExpireName: 'exp',
		serverTokenEndpoint: ENV.API_HOST + '/' + ENV.API_NAMESPACE + '/users/login',
		serverTokenRefreshEndpoint: ENV.API_HOST + '/' + ENV.API_NAMESPACE + '/users/login/refresh',
		identificationField: 'user_name',
		passwordField: 'password',
		authorizationPrefix: 'Bearer ',
		authorizationHeaderName: 'Authorization',
		headers: {}
	}
}
```

Before I updated Ember and auth packages, the header `Authorization: Bearer [token]` was automatically injected into all authenticated requests. After the update, only the login request works correctly, and all requests after it were not sending the `Authorization` header.

I read in the [ember-simple-auth README](https://github.com/simplabs/ember-simple-auth#authorizers) that authorization will not happen automatically for all requests the application issues anymore. So i looked for alternatives to work around this problem on the internet and read a suggestion to use Authorizers. But `ember-simple-auth` is deprecating Authorizers. So i found [here](https://github.com/jpadilla/ember-simple-auth-token/#sending-token-on-api-requests) a suggestion to extend the application adapter from `DataAdapterMixin`, and defining the property `authorizer: 'authorizer:token'`. Here's my application adapter:
```js
// app/adapters/application.js
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import config from '../../config/environment';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {

	authorizer: 'authorizer:token',

	host: config.API_HOST,

	namespace: config.API_NAMESPACE,

	shouldReloadAll() {

		return true;
	}
});
```
Apparently correct but still not working. It's as if Ember did not use this adapter to make the requests.

**My solution**: I changed my api lib to add the header `Authorization: Bearer [token]` into the ajax options if the user is authenticated. It worked.

**My problem**: When `ember-simple-auth-token` calls the API to refresh token, the `Authorization` header is **not** being sent, causing the user's session to be invalidated when attempting to update the token.

Any ideas? I've been breaking my head a few days ago to try to solve this.

Thanks.

**Comment by fenichelar** [comment]
> My problem: When ember-simple-auth-token calls the API to refresh token, the Authorization header is not being sent, causing the user's session to be invalidated when attempting to update the token.

@jzcorrea You can overwrite the `refreshAccessToken` method to get the behavior you desire:

```js
import { merge } from '@ember/polyfills';
import JWT from 'ember-simple-auth-token/authenticators/jwt';

export default JWT.extend({
  refreshAccessToken(token) {
    return new Promise((resolve, reject) => {
      const headers = merge(this.headers, {
        'Authorization': `Bearer ${token}`
      });
      this.makeRequest(this.serverTokenRefreshEndpoint, {}, headers).then(response => {
        try {
          const sessionData = this.handleAuthResponse(response);
          this.trigger('sessionDataUpdated', sessionData);
          return resolve(sessionData);
        } catch (error) {
          return reject(error);
        }
      }).catch(error => {
        this.handleTokenRefreshFail(error.status);
        return reject(error);
      });
    });
  }
});
```

**Comment by jzcorrea** [comment]
@fenichelar Thanks! I'll do this as soon as I upgrade to version 4.0.1. :call_me_hand:
