### ISSUE TITLE
Refresh Token request is setting the wrong token

### ISSUE THREAD

**Issue by kcaulfield94** [fenichelar/ember-simple-auth-token#221]
I have the minimal required setup going right now, with the refresh tokens. I see the refresh request get sent, and the api hands me back both an access token, and another refresh token for use prior to expiration of the current access token.

The plugin seems to take the refresh token (not the access token) from the response and use that token in future requests, which will fail.

Not sure if I am missing something here, or perhaps a version mismatch with my Ember version and/or simple auth version.

**Comment by jpadilla** [comment]
This might be resolved in master.

**Comment by kcaulfield94** [comment]
If so, are you planning a new release to npm? I would like to use this, but I cannot feel good about installing directly from master. NPM says published 5 months ago?

**Comment by fenichelar** [comment]
@kcaulfield94 Discussing - https://github.com/jpadilla/ember-simple-auth-token/pull/226#issuecomment-393612822
