### ISSUE TITLE
Each window refreshes token

### ISSUE THREAD

**Issue by fenichelar** [fenichelar/ember-simple-auth-token#228]
When using the JWT authentication, all open windows issue refresh requests. Only one refresh is needed. Not sure how best to improve this. I was thinking something along the lines of this:

1. Add a small amount of randomness to when refreshes are made otherwise all requests will be scheduled for the exact same time.
2. Before making a refresh, check that the token still needs to be refreshed. This check would be in the refresh function that is scheduled.
3. If the token has already been refreshed (`wait` > 0), don’t refresh, just schedule the next refresh.

**Comment by fenichelar** [comment]
@jpadilla What do you think about attempting to tackle this "issue"? I don't want to add any more complexity than needed and it isn't really an issue, but it would be nice to optimize this behavior.

**Comment by abhishek97** [comment]
@fenichelar We can wrap `refresh-token` call inside an `ember-concurrency` task and set max-concurrency to 1. Then again, we need to consider we want to depend upon it here.

**Comment by fenichelar** [comment]
@abhishek97 Does `ember-concurrency` span across tabs?

**Comment by Subtletree** [comment]
*just commenting to remove wontfix*

**Comment by evoactivity** [comment]
This can actually cause an issue depending on how the refresh tokens work from the api. I have opaque refresh tokens that exist within redis and once used are removed. If one tab wins the request race another tab can receive an expired token response and that will logout all of the tabs. It can also cause multiple tokens to be created for 1 user if everything happens before the delete occurs in redis.

I wonder if a service worker could be used to intercept all refresh token requests and return a cached response from the first successful refresh.

**Comment by fenichelar** [comment]
@evoactivity

> I wonder if a service worker could be used to intercept all refresh token requests and return a cached response from the first successful refresh.

Yes. You can extend the JWT authenticator and use a custom `refreshAccessToken` function: https://github.com/fenichelar/ember-simple-auth-token/blob/master/addon/authenticators/jwt.js#L183-L194.

**Comment by evoactivity** [comment]
I've solved this quite easily by adding [ember-master-tab](https://github.com/rhyek/ember-master-tab) and using my own authenticator like so.

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
// ember-simple-auth-token/authenticators/jwt is not typed
import { Registry, service } from '@ember/service';
import JWTAuthenticator from 'ember-simple-auth-token/authenticators/jwt';

export default class authenticator extends JWTAuthenticator {
  @service masterTab!: any;
  @service session!: Registry['session'];

  async refreshAccessToken(refreshToken: any, attempts: number) {
    // const response = this.masterTab.run(async () => {
    const data = this.makeRefreshData(refreshToken);

    const masterTab = this.masterTab.run(() => {
      return this.makeRequest(this.serverTokenRefreshEndpoint, data, this.headers)
        .then((response: any) => {
          const sessionData = this.handleAuthResponse(response.json);
          this.trigger('sessionDataUpdated', sessionData);
          return sessionData;
        })
        .catch((error: any) => {
          this.handleTokenRefreshFail(error.status, refreshToken, attempts);
          return Promise.reject(error);
        });
    });

    masterTab.else(() => {
      this.masterTab.contestMasterTab();
    });

    return (await masterTab.result) ?? this.session.data;
  }
}
```
This is the same strategy used by https://github.com/caiorasc/ember-implicit-grant-authenticator to ensure only 1 tab or window controls refreshing.

I had to [patch ember-master-tab](https://github.com/rhyek/ember-master-tab/issues/33) to make this use case work, but if they are happy landing that patch I think this is something that could be handled by the library if you're willing to take a PR @fenichelar

**Comment by fenichelar** [comment]
@evoactivity Thanks for the information. I really don't want to add any dependencies to this library. Because this library is designed to be extended, it should be easy for people to add this if they need it. I will take a look at how ember-master-tab works under the hood and see if I can built something similar internally. If not, then an example and link to ember-master-tab in the readme will probably be the way forward.
