### ISSUE TITLE
Fit to a backend with differen identification field

### ISSUE THREAD

**Issue by tpetrone** [fenichelar/ember-simple-auth-token#233]
Now that `config.identificationField` and `config.passwordField` have been removed how am I supposed to fit in a backend that uses `email` as the identification field?

**Comment by fenichelar** [comment]
You can pass any object into `authenticate`. I.e. `{email: 'test@example.com', password: 'password'}` and the entire object will be sent to the server as it. See example here: https://github.com/jpadilla/ember-simple-auth-token/blob/master/tests/dummy/app/controllers/login.js

**Comment by knownasilya** [comment]
This should probably be mentioned in the Upgrade Notes section in the readme.
