### ISSUE TITLE
Overriding Token Property Name No Longer Works

### ISSUE THREAD

**Issue by thegranddesign** [fenichelar/ember-simple-auth-token#244]
I think there's a typo where the configuration option was changed to `tokenDataPropertyName` but there are still references to `tokenPropertyName` [here](https://github.com/jpadilla/ember-simple-auth-token/search?q=tokenPropertyName&unscoped_q=tokenPropertyName) and because it's always `null`, the default is always used.

**Comment by fenichelar** [comment]
`tokenPropertyName` is still the correct config setting to use. `tokenDataPropertyName` is a different setting.

I just overwrote `tokenPropertyName` to `token2` and it worked as expected.

**Comment by fenichelar** [comment]
@thegranddesign I'm going to close this, let me know if you are still experiencing issues.

**Comment by thegranddesign** [comment]
@fenichelar well the README states otherwise: https://github.com/jpadilla/ember-simple-auth-token/search?q=tokendatapropertyname&unscoped_q=tokendatapropertyname

**Comment by fenichelar** [comment]
Please explain how the readme states otherwise? From the readme:

```
tokenPropertyName: 'token', // Key in server response that contains the access token
tokenDataPropertyName: 'tokenData'; // Key in session to store token data
```

What are you attempting to do? If you are attempting to change the property in the server response that contains the token, use `tokenPropertyName`. If you are attempting to change the property in the session that contains the decoded token data, use `tokenDataPropertyName`.

**Comment by thegranddesign** [comment]
@fenichelar Ah I see now.  IMO the README is unclear.  It would be better to just repeat the settings for each type.  Additionally some alignment of the values would make things much more readable:

```js
ENV['ember-simple-auth-token'] = {
  tokenDataPropertyName: 'tokenData'; // Key in session to store token data
  refreshAccessTokens: true, // Enables access token refreshing
  tokenExpirationInvalidateSession: true, // Enables session invalidation on token expiration
  serverTokenRefreshEndpoint: '/api/token-refresh/', // Server endpoint to send refresh request
  refreshTokenPropertyName: 'refresh_token', // Key in server response that contains the refresh token
  tokenExpireName: 'exp', // Field containing token expiration
  refreshLeeway: 0 // Amount of time to send refresh request before token expiration
};
```

versus

```js
ENV['ember-simple-auth-token'] = {
  tokenDataPropertyName:            'tokenData',           // Key in session to store token data
  refreshAccessTokens:              true,                  // Enables access token refreshing
  tokenExpirationInvalidateSession: true,                  // Enables session invalidation on token expiration
  serverTokenRefreshEndpoint:       '/api/token-refresh/', // Server endpoint to send refresh request
  refreshTokenPropertyName:         'refresh_token',       // Key in server response that contains the refresh token
  tokenExpireName:                  'exp',                 // Field containing token expiration
  refreshLeeway:                    0                      // Amount of time to send refresh request before token expiration
};
```

Thanks for the response!
