### ISSUE TITLE
[Fastboot] atob() global function is not available in Node.js environment

### ISSUE THREAD

**Issue by musaffa** [fenichelar/ember-simple-auth-token#247]
`atob` global function [used](https://github.com/jpadilla/ember-simple-auth-token/blob/5102353fc2178582c3f9aaa86fa12995a6072603/addon/authenticators/jwt.js#L221) in jwt authenticator is only a browser specific implementation. We get a reference error when calling `atob` in Fastboot's Node.js environment.

A possible solution is to use an isomorphic implementation of `atob`. For example: [abab](https://github.com/jsdom/abab).

**Comment by fenichelar** [comment]
@musaffa Mmmm, I'm not sure I understand the use case. If you are calling `getTokenData` (either directly or indirectly) on the server, what session data would be used?

**Comment by musaffa** [comment]
Cookie store. See [Fastboot](https://github.com/simplabs/ember-simple-auth#fastboot) section of Ember Simple Auth's readme.

**Comment by fenichelar** [comment]
@musaffa Does #248 fix your issue?

**Comment by musaffa** [comment]
No it doesn't. I've tested this commit in a Fastboot application. I've also shared my observation on that PR.
