### ISSUE TITLE
Could not find module `fetch` 

### ISSUE THREAD

**Issue by Uysim** [fenichelar/ember-simple-auth-token#257]
It happen when I upgrade ember-cli to lastest verions
```
Could not find module `fetch` imported from `ember-simple-auth-token/authenticators/
```

Packages
```
ember-cli: 3.5.1
ember-cli-fastboot: 2.0.0
ember-simple-auth-token: 4.0.5
```

**Comment by fenichelar** [comment]
I see you are using fastboot, have you added `node-fetch` to your `fastbootDependencies` as described [here](https://github.com/simplabs/ember-simple-auth#fastboot)?

**Comment by Uysim** [comment]
@fenichelar  Yes I did

**Comment by Uysim** [comment]
I also try to `import fetch from 'fetch'` in my application model. It is fine

**Comment by fenichelar** [comment]
Can you provide an example application that demonstrates the issue? I'm not able to reproduce it.

**Comment by Uysim** [comment]
I try to reproduce it at https://github.com/Uysim/reproduce-fetch-module

**Comment by fenichelar** [comment]
@Uysim Thank you. I am able to reproduce the issue with that repo. However, I haven't been able to figure out the problem... @jpadilla Thoughts?

**Comment by Uysim** [comment]
I don't know whether it is relate to this https://github.com/ember-cli/ember-fetch#use-with-fastboot

**Comment by gregorymark** [comment]
Looks like it's related to 
https://github.com/ember-cli/ember-fetch/issues/62
and
https://github.com/simplabs/ember-simple-auth/issues/1138

And going from the end of that second issue, install `ember-fetch` separately just using
`ember install ember-fetch` seems to make it work nicely.

**Comment by Uysim** [comment]
@gregorymark  Yes I fixed it by to ember install ember-fetch. Thank you

**Comment by Uysim** [comment]
``
