### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jherdman** [fenichelar/ember-simple-auth-token#263]
Is it possible to get a new release that includes all of the changes in master?

**Comment by jpadilla** [comment]
@fenichelar any chance you could put together a PR for a new release?

**Comment by fenichelar** [comment]
Working on it now

**Comment by jpadilla** [comment]
@jherdman just released v4.0.7 thanks to @fenichelar

**Comment by jherdman** [comment]
Much love to you both!
