### ISSUE TITLE
TokenAuthorizerMixin doesn't work with Octane (without jQuery)

### ISSUE THREAD

**Issue by BryanHunt** [fenichelar/ember-simple-auth-token#266]
When you disable jQuery (Octane preview builds fail when jQuery is enabled) to use Octane, TokenAuthoirzerMixin will not put the Bearer token into the request header.  The root cause is in how EmberData uses fetch() and how ember-simple-auth hooks the request.  See: https://github.com/simplabs/ember-simple-auth/issues/1961 for details and a work around.

**Comment by gte451f** [comment]
I can confirm this remains a problem for me.  I've followed the steps outlined in the workaround instead of using this plugin.
