### ISSUE TITLE
Adapter vs Authorizer mixin, which one to use?

### ISSUE THREAD

**Issue by stopfstedt** [fenichelar/ember-simple-auth-token#279]
Hi there, 
From looking at the README, it is not clear to me whether I should use the new adapter or authorizer mixin.

They seem to be serving the same purpose.

> In order to send the token with all API requests made to the server, the token adapter mixin should be used:
> ...
> The mixin will add the header to each API request:
> ...

vs

> In order to send the token with all API requests made to the server, the token authorizer mixin should be used:
> ...
> The mixin will add the header to each API request:
> ...

When/where would I use one over the other?

Thank you.

**Comment by Subtletree** [comment]
Yeah needs some clarification in the docs.

The authorizer mixin is older and should be used with `ember-simple-auth` prior to 3.0.0.

Use the adapter mixin for `ember-simple-auth` 3.0.0 onwards.

**Comment by fenichelar** [comment]
@Subtletree thank you. I have updated the readme.

**Comment by Subtletree** [comment]
Thanks @fenichelar! Sorry I should have just updated the readme myself!

**Comment by fenichelar** [comment]
@Subtletree I needed to update some packages anyways.
