### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by jpadilla** [fenichelar/ember-simple-auth-token#28]
A live running demo/example of this would be great. It should help visualize what is going on.

**Comment by erichaus** [comment]
@jpadilla let me know if you want any help setting it up? Ive set up a few drf/ember-cli projects on heroku now using this.. not too painful

**Comment by jpadilla** [comment]
@erichonkanen before actually doing anything I'd like to figure out what would help others understand JWT + Authentication in general using this package and `djangorestframework-jwt` and figure out how we can visually demonstrate how it works.

**Comment by jdhoek** [comment]
For JWT, showing the contents of the token would be a big plus. I like what http://jwt.io/ does in terms of visualising the content bit of the token.

**Comment by jpadilla** [comment]
First attempt at this using a dummy app.

https://jpadilla.github.io/ember-cli-simple-auth-token/

**Comment by erichaus** [comment]
@jpadilla looks good... are you using CORS for that? just curious bc I notice the OPTIONS pre-flight request... on my heroku apps I have been using proxy between backend django / client ember.. interested to know how you set that up...

as far as the blacklist subapp PR on django side, a simple demo of it could be as easy as a button to blacklist yourself which makes the request to auth-token-blacklist endpoint (should log you out after next refresh attempt)... Or if you have another idea to tie it in let me know. Originally I was thinking to make another addon to this that included an activity-based timer that would issue the blacklist request if it counted down to 0. The use case I described previously could be expanded to when you need to ensure someone's access is revoked immediately

**Comment by jpadilla** [comment]
@erichonkanen yea using CORS. The API is just a simple express app that mimics what we're doing for the mock endpoints here. For Django, you might want to try using [django-cors-headers](https://github.com/ottoyiu/django-cors-headers).

That sounds good. I'll probably write a demo based on this that uses DRF+JWT so we can try out the new things including blacklisting. Will try to do that this weekend.

**Comment by erichaus** [comment]
@jpadilla sounds good... let me know if I can help with anything.. it's interesting Im working on a new project using microservices and the topic of blacklisting came up and I got input that it'd be useful although as someone on the drf thread stated it might be difficult in a services architecture.. I think since it's an optional feature and just has a base implementation, it leaves it open ended

**Comment by jpadilla** [comment]
@erichonkanen feel free to take this one if you'd like. I haven't had as much time as I'd hope for it. IM me if you want to chat about it.

**Comment by erichonkanen** [comment]
@jpadilla which version of this package is the demo using? if it is using the latest tagged release 0.7.2 with ember-simple-auth 0.8.0-beta.2+ then that might clue me in that my local test app is broken in relation to the [ongoing issue with restore](https://github.com/jpadilla/ember-cli-simple-auth-token/issues/71)
