### ISSUE TITLE
fetch is not defined - maybe your browser targets are not covering everything you need

### ISSUE THREAD

**Issue by BryanHunt** [fenichelar/ember-simple-auth-token#283]
I'm upgrading my applications to Ember 3.20 and I have run into this error:

`fetch is not defined - maybe your browser targets are not covering everything you need`

The root cause is the dependency to ember-fetch 6.7.2 in ember-simple-auth-token.  The fix is to force the dependency to resolve to ember-fetch 8.0.2.

```json
  "resolutions": {
    "ember-simple-auth-token/ember-fetch": "^8.0.2"
  },
```

**Comment by fenichelar** [comment]
@BryanHunt In order to retain backwards compatibility, we can't force any specific version of `ember-fetch`. `ember-simple-auth-token` only supported `ember-fetch` v4, v5, and v6. By adding support for v8, this issue should be resolved.
