### ISSUE TITLE
Demo app not working due to CORS issue

### ISSUE THREAD

**Issue by eelke** [fenichelar/ember-simple-auth-token#287]
Attempting the login in the demo on Chrome yields the following errors:

`Access to XMLHttpRequest at 'https://simple-auth-token-server.herokuapp.com/api/token-auth/' from origin 'https://jpadilla.github.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by fenichelar** [comment]
@jpadilla Can you update the Heroku CORS policy to allow requests from `https://jpadilla.github.io`?

**Comment by jpadilla** [comment]
thanks, should be working now.
