### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by fenichelar** [fenichelar/ember-simple-auth-token#292]
@jpadilla Travis CI Integration is not working. It looks like the remediation steps are described [here](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154). I do not have the necessary permissions on the GitHub repository. Can you please take a look?

`travis-ci.org` is going away. Do you want to migrate to `travis-ci.com`, CircleCI, GitHub Actions, or something else?

**Comment by jpadilla** [comment]
Thanks for the heads up!

Just followed the migration dance for this repo. I'm assuming new PR's will trigger the current status checks. https://travis-ci.com/github/jpadilla/ember-simple-auth-token

We _could_ move to GH Actions, not sure how much effort it'd take to do so.
