### ISSUE TITLE
Jwt doesn't work out of the box with ember-cli.

### ISSUE THREAD

**Issue by techiemac** [fenichelar/ember-simple-auth-token#30]
Using the latest version of ember-cli (0.1.15), the latest install steps do not seem to be working when using JWT (simple-auth-authenticator:jwt). 

I ran the following steps in a clean dummy project:

```
npm install --save-dev ember-cli-simple-auth
ember generate ember-cli-simple-auth
npm install --save-dev ember-cli-simple-auth-token
ember generate simple-auth-token
```

Following this, I created the login route and controller for jwt authentication per the steps listed in the README.md.

Once I try to login, I get the following error in chrome:

```
Uncaught Error: Assertion Failed: No authenticator for factory "simple-auth-authenticator:jwt" could be found
```

**Comment by techiemac** [comment]
I see what I did wrong here. I'm a bit too bleeding edge :)

It looks like jwt is not yet in the NPM repository so I pulled down the latest master branch. I look forward to the npm repo update!

**Comment by jpadilla** [comment]
@techiemac woops, sorry about, should've had merged that into another branch instead of master.

**Comment by gdong42** [comment]
@techiemac Can you please elaborate more what was the problem and how to solve it? I had exactly the same problem but could not figure out what went wrong.

Thanks

**Comment by corrspt** [comment]
What versions of Ember, EmberSimpleAuth and SimpleAuthToken are you using (I also had some issues making this work with the latest ember, maybe I can help)

**Comment by gdong42** [comment]
DEBUG: -------------------------------
ember.debug.js:5332DEBUG: Ember                       : 1.13.5
ember.debug.js:5332DEBUG: Ember Data                  : 1.13.7
ember.debug.js:5332DEBUG: jQuery                      : 1.11.3
ember.debug.js:5332DEBUG: Ember Simple Auth           : 0.8.0

SimpleAuthToken is the latest 0.7.3.

Thanks @corrspt , never mind, though. I'm able to go through it.. I was stuck on this for hours and just to find that restarting ember app solved it!  I feel so frustrated.

For anyone who runs into the same issue as I have, restart the ember application might help. Auto-reloading seems does not help in this case.

**Comment by csprocket777** [comment]
I'm experiencing this issue when deploying from a CI server. Locally it builds and runs just fine. When the CI builds it and deploys it I get this error. How do I debug this? What's going on?
