### ISSUE TITLE
Addon incompatible with latest version of ember-simple-auth

### ISSUE THREAD

**Issue by maxymczech** [fenichelar/ember-simple-auth-token#302]
This pull request has removed `setup-session-service`: https://github.com/simplabs/ember-simple-auth/pull/2315

Rendering `ember-simple-auth-token` incompatible.

**Comment by maxymczech** [comment]
I apologize, after further investigation I can elaborate. I am using new `embroider` build system with `webpack`. After updating `ember-simple-auth` to version `4.0.0` the app I am working on was broken. The reason for this, as it seems, is simply that you don't have `ember-simple-auth@4.0.0` in your dependencies list:

`"ember-simple-auth": "^1.6.0 || ^2.0.0 || ^3.0.0"`

The app works fine if I revert back to classic build, and it also works if I try and add `^4.0.0` to that dependency version list. I hope this could be just as easy as that.

**Comment by fenichelar** [comment]
@maxymczech Yes, `ember-simple-auth@v4` isn't supported yet. I hope to work on this in the next few weeks.

**Comment by fenichelar** [comment]
`ember-simple-auth-token@v5.3.0` supports `ember-simple-auth@v4`
