### ISSUE TITLE
Transferring Ownership

### ISSUE THREAD

**Issue by jpadilla** [fenichelar/ember-simple-auth-token#306]
Creating this to track transferring ownership of this library and any of assets tied to it over to @fenichelar. Thanks again for all your help through the years!

**Comment by fenichelar** [comment]
@jpadilla please let me know what you need from me. Thank you.

**Comment by jpadilla** [comment]
@fenichelar you'll need to delete your fork before I can transfer the repository.

**Comment by fenichelar** [comment]
@jpadilla I deleted the fork.

**Comment by fenichelar** [comment]
@jpadilla I have setup the demo app under `https://fenichelar.github.io/ember-simple-auth-token/`. What do I need to do about the Heroku portion of the demo?

**Comment by jpadilla** [comment]
@fenichelar I can also transfer that over to you if you have a heroku account, if so same email from your profile?

**Comment by fenichelar** [comment]
@jpadilla I have a Heroku account, same email.

**Comment by jpadilla** [comment]
Initiated transfer for Heroku app and that repo https://github.com/jpadilla/ember-simple-auth-token-server

**Comment by fenichelar** [comment]
@jpadilla Received. I believe the Heroku app is all set.
