### ISSUE TITLE
Release 0.6.0 not found on npm

### ISSUE THREAD

**Issue by dnbkr** [fenichelar/ember-simple-auth-token#31]
When I go to install with `ember install:addon ember-cli-simple-auth-token@0.6.0` I get the error `version not found: ember-cli-simple-auth-token@0.6.0
Error: version not found: ember-cli-simple-auth-token@0.6.0`
And also npmjs.com doesn't know about 0.6.0 - not sure what's gone wrong as your package.json is 0.6.0

**Comment by jpadilla** [comment]
Sorry, must have forgotten to publish it to NPM.
