### ISSUE TITLE
JWT automatic refresh, configurable interval?

### ISSUE THREAD

**Issue by jdhoek** [fenichelar/ember-simple-auth-token#32]
The automatic refresh for JSON Web Tokens works, but it is cutting it kind of close by refreshing at the absolute last second that the previous token is still valid. Just a bit of lag could cause the old token to reach the API server in an expired state.

I would like to refresh the token a little while before the old one expires. Can this margin be made a configurable parameter?

**Comment by erichaus** [comment]
@jdhoek seems like a good feature... when I was building that I was using a [django backend jwt package](https://github.com/GetBlimp/django-rest-framework-jwt) that has a jwt_leeway setting which I had set to 3 seconds.. It makes sense to have that in this package as well
