### ISSUE TITLE
Support for ESA v5 and v6

### ISSUE THREAD

**Issue by jrjohnson** [fenichelar/ember-simple-auth-token#326]
package.json lists support up to v4 of ESA, but v5 was released in March and v6-rc1 has just been published https://github.com/mainmatter/ember-simple-auth/blob/master/CHANGELOG.md

**Comment by fenichelar** [comment]
Added support for ESA v5. Release candidates are not supported.

I can't create a release and publish until GitHub outage is resolved because GitHub Actions are not working. Hopefully later today I will be able to publish v5.3.2.
