### ISSUE TITLE
Thoughts on dropping support for very old ember and simple auth?

### ISSUE THREAD

**Issue by jrjohnson** [fenichelar/ember-simple-auth-token#329]
I was looking at running an update to at least ember-cli 4.12, however it's going to maybe require dropping support for ember versions before 4.x and node before 14.x along with most of the old ESA versions. Before I get into it I wanted to see how you'd feel about that? I think it is completely reasonable for this add-on to only work with versions of ember and ESA that are supported. Anyone who still needs support for older releases can simply pin their version of this library.

**Comment by fenichelar** [comment]
A major overhaul is in the works including:
- Support for ember@4 and ember@5
- V2 format
