### ISSUE TITLE
Updating the addon

### ISSUE THREAD

**Issue by AmauryD** [fenichelar/ember-simple-auth-token#330]
Hello, 

Do you need assistance in transitioning this addon to use modern Ember syntax? This involves several key modifications, including:
    - Eliminating deprecated Mixins.
    - Discontinuing support for older Node and ember-simple-auth versions.
    - Modernizing the existing Ember syntax and refreshing the dummy app.
    - V2 format ?

These changes will be obviously breaking changes.

**Comment by SanderKnauff** [comment]
@fenichelar apologies for the ping.

This addon seems to be incompatible with the lastest version of Ember 5 and `ember-simple-auth`.
There does not seem to have been a lot of activity recently in this respository. If there are any PRs opened to solve the compatibility issues, would you mind taking a look at them and merging them?

We are relying on this addon at my work and it is blocking us from upgrading to Ember 5. I wouldn't mind putting in some work to get it compatible, but I would like to know if contributions will be accepted before putting in the effort. :sweat_smile:

**Comment by AmauryD** [comment]
I already began to work on this when i made this issue. It works but i need to repair the CI and maybe some tests (I don't remember it was 3 months ago). It can be installed using `@triptyk/ember-simple-auth-token` package.
Here's the repo:  https://github.com/AmauryD/ember-simple-auth-token

**Comment by SanderKnauff** [comment]
> I already began to work on this when i made this issue. It works but i need to repair the CI and maybe some tests (I don't remember it was 3 months ago). It can be installed using `@triptyk/ember-simple-auth-token` package. Here's the repo: https://github.com/AmauryD/ember-simple-auth-token

Oh nice! With a bit of luck (and fixes for the tests) this could be merged upstream!

**Comment by AmauryD** [comment]
Tracked by https://github.com/fenichelar/ember-simple-auth-token/pull/334.
The tests are OK. Still need to investigate fastboot compatibility. I removed it 3 months ago because it was not working 😅  .

**Comment by AmauryD** [comment]
Everything is kinda OK. I'm waiting for a feedback of @fenichelar before spending more time on this. 
Only the `embroider-optimized` scenario is failing because of a bug with fastboot. Should be fixed upstream soon.

**Comment by fenichelar** [comment]
A major overhaul is in the works including:
- Support for ember@4 and ember@5
- V2 format

**Comment by AmauryD** [comment]
> A major overhaul is in the works including:
> 
> * Support for ember@4 and ember@5
> * V2 format

Does this make this PR #334 obsolete ?

**Comment by AmauryD** [comment]
@fenichelar thank's for the work !
