### ISSUE TITLE
Token resolve fails on every page refresh.

### ISSUE THREAD

**Issue by RSNara** [fenichelar/ember-simple-auth-token#35]
[Line 87 looks really strange.](https://github.com/jpadilla/ember-cli-simple-auth-token/commit/eceb343223256868e1bcb8210941d134d8659e01)

Shouldn't we refresh the token if data.expiresAt < Date.now()?

**Comment by jpadilla** [comment]
@ramanpreetnara If you do find something wrong with that, a failing test would be amazing.

**Comment by erichaus** [comment]
@ramanpreetnara that is checking that the expiration date is in the future (not expired) before proceeding to schedule a token refresh, the actual time the refresh occurs is calculated after...

It was also changed slightly in a recent PR:
https://github.com/jpadilla/ember-cli-simple-auth-token/pull/33/files#diff-b3b19e97b14851cfabb1e6558abfc6daR196

**Comment by RSNara** [comment]
@erichonkanen that clears things up, thanks!
