### ISSUE TITLE
When setting Token Prefix to empty default shows up

### ISSUE THREAD

**Issue by wieseljonas** [fenichelar/ember-simple-auth-token#4]
I don't have any token prefix. The only way I could make it work is to hard code the authorize code.

If I set authorizationPrefix to empty the default 'Bearer ' still shows up in the request.

```
 authorizationPrefix: '',
```

**Comment by jpadilla** [comment]
@wieseljonas Check out https://github.com/jpadilla/ember-cli-simple-auth-token/commit/addf32450d9e8b93c0161bc1057622b607383212.

Just released a new version with those changes.
