### ISSUE TITLE
Header or body?

### ISSUE THREAD

**Issue by sedovalx** [fenichelar/ember-simple-auth-token#40]
Can you explain me please the purpose of using both request header and response body in the token exchange? If i'm not mistaken when the client makes authentication or renew call this library expects the token to be in the body of server response. On the other hand an authorizer puts the token into header of a request. Why not always use header-based approach?

Update:
May be would be better to use more generic approach when taking the token from response or putting into request. It will give a useroptions - put/get the token into the request/response body or user specified header.

**Comment by jpadilla** [comment]
@sedovalx Traditionally this is how it's always been. Authorization is sent to the server via a query parameter or header. A client sending credentials to the server would most likely expect to receive data in the response body. I'm not sure I've ever seen a case where the client has to check the response headers for data like a token.

I guess there's nothing wrong with doing it that way. We're just following the most common patterns.
