### ISSUE TITLE
Should this still work with the latest ember?

### ISSUE THREAD

**Issue by wayne-o** [fenichelar/ember-simple-auth-token#42]
The authenticator doesn't get registered after I run the `ember generate simple-auth-token` command...

I know there has been a lot of work around the add-ons area of ember-cli and I wonder if this is because of that?

**Comment by jpadilla** [comment]
@wayne-o could you run `ember version` and report back?

**Comment by wayne-o** [comment]
here you go mate:

```
version: 0.2.2

A new version of ember-cli is available (0.2.3). To install it, type ember update.
node: 0.12.0
npm: 2.7.4

```

**Comment by wayne-o** [comment]
I have noticed as well that my adapters/application.headers never gets called

**Comment by wayne-o** [comment]
OK so the issue was i hadn't amended the token name property correctly - apologies for the noise
