### ISSUE TITLE
timeFactor default value and documentation

### ISSUE THREAD

**Issue by engwan** [fenichelar/ember-simple-auth-token#47]
So, I started using this and was wondering why my tokens weren't being refreshed automatically.

Turns out it was because the `timeFactor` was set incorrectly. My server returned expiry times in seconds (Unix time).

It took me a while to track the problem because I assumed `timeFactor` to be correctly set to 1 because the docs say that the default value of 1 refers to seconds:

```
  /**
    Default time unit.
    @property timeFactor
    @type Integer
    @default 1 (seconds)
  */
  timeFactor: 1,
```

Then I saw the code comparing the expiry time to JS `getTime()` which is in milliseconds.

Since the JWT spec specifies that the time should be in seconds, shouldn't the default be 1000?

**Comment by erichaus** [comment]
@engwan I think I had set that to 1 just because javascript uses milliseconds by default but I don't have a problem setting it to 1000 since my backend also sends time out in seconds

**Comment by erichaus** [comment]
@engwan do you think it would be better to have a more verbose and strict value, instead of `timeFactor` it could be something like `backendServerTimeUnit: seconds`?

**Comment by engwan** [comment]
Yes, I think that would be much better. 99% of the time it's gonna be either seconds or milliseconds.

I don't think anyone would use timeFactor values other than 1 or 1000 :)

**Comment by erichaus** [comment]
@jpadilla what do you think? ill submit pr if it makes sense... still haven't caught up with latest changes to this library but im about to as im using it in active project...

**Comment by jpadilla** [comment]
@erichonkanen not entirely sure what the proposal here is? Better documentation around `timeFactor`? Setting `timeFactor` to `1000`?

**Comment by erichaus** [comment]
@jpadilla instead of having timeFactor be an integer value, one proposal would be to have e.g. two values you can use for it with one being the default:

`timeFactor: seconds` or
`timeFactor: milliseconds`

Those are the only two cases anyways and it's easier to understand if it's verbose as a word. The variable name could be adjusted also to e.g.:

`serverTimeUnit: seconds`

**Comment by jpadilla** [comment]
@erichonkanen I feel like this can actually just be solved with better docs/examples instead of adding more config/settings. Thoughts?

**Comment by erichaus** [comment]
@jpadilla the reason I like the idea of switching from `timeFactor` to a more semantic `serverTimeUnit` is that there are really only 2 cases which are seconds and milliseconds... So right now someone is either going to set it to 1 (seconds) or 1000 (milliseconds), but that seems more confusing that just saying hey either you set it to the verbose "seconds" or "milliseconds".. the name could remain the same as `timeFactor` even
