### ISSUE TITLE
refreshLeeway

### ISSUE THREAD

**Issue by brandonparsons** [fenichelar/ember-simple-auth-token#48]
Hi there,

`refreshLeeway` is documented as an option, but it doesn't appear that this property appears anywhere in the library code.

Am I missing something?

**Comment by jpadilla** [comment]
Not sure what you mean. Search for [refreshLeeway](https://github.com/jpadilla/ember-cli-simple-auth-token/search?utf8=%E2%9C%93&q=refreshLeeway).

Update: Do you have an older installed version?

**Comment by brandonparsons** [comment]
`Update: Do you have an older installed version?`

Perhaps... Not quite sure now :)
