### ISSUE TITLE
buildToken(): session.[tokenPropertyName] or session.secure.[tokenPropertyName]?

### ISSUE THREAD

**Issue by ericestes** [fenichelar/ember-simple-auth-token#53]
It looks like buildToken() is looking for the token in session.[tokenPropertyName], which fails because the token is saved in session.secure.[tokenPropertyName]. This is preventing the token from being passed in the Authorization header.

Should buildToken() be looking in session.secure? Or is there a config error on my end?

**Comment by engwan** [comment]
I'm also experiencing this issue after upgrading ember-simple-auth.

It's actually a breaking change in 0.8.0-beta.1

From https://github.com/simplabs/ember-simple-auth/releases

The secure session data is now stored under the special key secure, see #414. This makes sure that the session isn't cleared completely on logout but only the secure key instead. This is a [BREAKING] change if you're using a custom authorizer as that must fetch the token etc. from the session's secure key now.

It's solved here:

https://github.com/jpadilla/ember-cli-simple-auth-token/pull/49

**Comment by jpadilla** [comment]
Apparently I had fixed this a while back but never pushed changes. Could you try with latest master which also uses `0.8.0-beta.2`?

**Comment by jpadilla** [comment]
Deployed v0.7.1
