### ISSUE TITLE
Opening the same app in multiple tabs - refresh gets confused

### ISSUE THREAD

**Issue by brandonparsons** [fenichelar/ember-simple-auth-token#57]
For some reason, if I open my app in two tabs simultaneously, `ember-cli-simple-auth-token` starts requesting refreshes at an insane rate (i.e. floods my development server).

Am I doing something wrong?

```
Scheduling access refresh for 1432182535
10jwt.js:213 Scheduling access refresh for 1432182536
10jwt.js:213 Scheduling access refresh for 1432182537
11jwt.js:213 Scheduling access refresh for 1432182538
10jwt.js:213 Scheduling access refresh for 1432182539
10jwt.js:213 Scheduling access refresh for 1432182540
11jwt.js:213 Scheduling access refresh for 1432182541
10jwt.js:213 Scheduling access refresh for 1432182542
8jwt.js:213 Scheduling access refresh for 1432182543
10jwt.js:213 Scheduling access refresh for 1432182544
10jwt.js:213 Scheduling access refresh for 1432182545
12jwt.js:213 Scheduling access refresh for 1432182546
8jwt.js:213 Scheduling access refresh for 1432182547
9jwt.js:213 Scheduling access refresh for 1432182548
```

**Comment by jpadilla** [comment]
@erichonkanen have you experienced this issue? Any ideas what it could be?

**Comment by brandonparsons** [comment]
Any help you could provide would be appreciated. Does this not happen to you on your apps?

This is obviously a bit of a blocker as I don't want to DDOS myself :)

**Comment by erichaus** [comment]
hola, hmm definitely shouldn't be doing that.. it was an issue in the past but was resolved. That said I havent pulled latest code so maybe something broke again.. @brandonparsons you have latest code?

**Comment by leejt489** [comment]
May be related, but I'm also seeing that if the `expirePropertyName` is set, that I am unauthenticated immediately on a refresh.  If I set the `expirePropertyName` to the wrong name, it authenticates requests fine, but of course it doesn't actually trigger a logout after the token expires.

**Comment by erichaus** [comment]
@brandonparsons can you paste your settings for this package? what is your backend? do you know what your jwt token expire is set to? is it coming from backend in seconds (e.g. python backend) or milliseconds (e.g. javascript based)?

I just pulled the latest code (0.7.1) and I do not get these issues.. I can open multiple tabs and refresh the page and it works as expected.. let me know and I'll look into it more

**Comment by erichaus** [comment]
@leejt489 do you mean `tokenPropertyName`? `expirePropertyName` isn't a config value...

**Comment by leejt489** [comment]
Sorry, I mean `tokenExpireName`.

**Comment by brandonparsons** [comment]
Hi there, sorry - was out and about and just saw this. I might be using old code. Let me try to update it. (I'm used to bundler and not NPM :) )

**Comment by brandonparsons** [comment]
Well I'm definitely using old code (I was on `0.6`). I've tried updating to 0.7.1 but now I'm getting a bunch of errors, probably because I need to update `ember-simple-auth` as well. WIll get back to you.

**Comment by brandonparsons** [comment]
Yep - this is on me. I was using an old version of this package. I upgraded simple-auth and simple-auth-token and I am no longer receiving this error.

Thank you for the quick reply!

/cc @erichonkanen @leejt489
