### ISSUE TITLE
Controllers

### ISSUE THREAD

**Issue by ghost** [fenichelar/ember-simple-auth-token#58]
Hi there. 
As the controllers are going to be deprecated soon, there's a way to get rid of the `login` controller?

Thanks

**Comment by jpadilla** [comment]
@daminufe an example might be you have a login route / component. Your component can do something like:

``` javascript
this.sendAction('login', this.getProperties('username', 'password'));
```

your route would have a `login` action that would do:

``` javascript
var credentials = this.getProperties('identification', 'password'),
  authenticator = 'simple-auth-authenticator:jwt';

this.get('session').authenticate(authenticator, credentials);
```

makes sense?
