### ISSUE TITLE
Sending JWT token with ember-data requests?

### ISSUE THREAD

**Issue by nesevis** [fenichelar/ember-simple-auth-token#61]
How would I accomplish this?

I assume it would go in the headers inside the RESTAdapter, but where do I import the token from?

**Comment by nesevis** [comment]
Figured it out: https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth#cross-origin-authorization (add your API to the the CrossOriginWhitelist)

**Comment by ghost** [comment]
The link is broken.

> To include authorization info in all Ember Data requests if the session is authenticated, mix the DataAdapterMixin into the application adapter.

```
// app/adapters/application.js
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:oauth2'
});
```
