### ISSUE TITLE
getting the authenticated user

### ISSUE THREAD

**Issue by ghost** [fenichelar/ember-simple-auth-token#63]
Hey man I've been searching online but there's not a lot of resources. Is the any way to get the current authenticated user information? The specific example is in a route:

```
export default Ember.Route.extend({

    model: function(){

        return this.store.find('cart', "I want to pass in the current users id")

    }

});
```

any way for me to accomplish this?

**Comment by jpadilla** [comment]
@threeaccents you can access the simple auth's session by doing `this.get('session')`. As of recently you'd probably want to do `this.get('session.secure')`.
