### ISSUE TITLE
local storage getting cleared after refresh

### ISSUE THREAD

**Issue by ghost** [fenichelar/ember-simple-auth-token#65]
Hey man this might be an issue with ember simple auth and not your token addon. I have a fresh install of both and a simple login set up it works fine but once I refresh it logs me out every time. I made a repo for the app to show you. https://github.com/threeaccents/enjoy_louville_app, I even created a new ember app to see if it was maybe anything I had done and just installed those 2 plugins and same error occurred.

Here is the resource generated by simple auth:

`{"secure":{"authenticator":"simple-auth-authenticator:jwt","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.eyJzdWIiOiIyIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjgwMDBcL2FwaVwvdjFcL2F1dGhlbnRpY2F0ZSIsImlhdCI6IjE0MzQyMTU2MjkiLCJleHAiOiIxNDM0MjE2MjI5IiwibmJmIjoiMTQzNDIxNTYyOSIsImp0aSI6IjBkOWQ4OTA2Y2YyNDQ2YmZkMDEyOTI5MzhmNzc4MjkyIn0.MzhjNzZkOGI2MDZiOWFlMzE2NzM2YTVlMDhhZjQ1ODMwZjVlYWZlOTcyMDhjZjAzNTRhNzA2MzY2MzQzYzM5Mw","expiresAt":"1434216229"}}`

The issue was occurring because I had to change the `timeFactor` to 1000. There should be a check to see if the expires at length is the correct one.

I added a simple if statement:

`if(expiresAt.length !== 13){
   return reject(new Error('Invalid expiration'));
}`

I'm sure there could be a much better check. The other idea I had was instead of the user decideing the timeFactor there could be a simple function that counts the length of the `exp` and then just adds as many 0's as necessary for it to match the `now` variable.

**Comment by jpadilla** [comment]
@threeaccents thanks for putting this together. This is biting others as well, see #47. I'm thinking we either change the default value to `1000` or set it to null and whoever wants to use refresh has to explicitly set a valid value. As far as I've seen, I think the common value people are using is `1000`.

@erichonkanen thoughts?

**Comment by ghost** [comment]
@erichonkanen @jpadilla I would probably just do it ember style and change it to 1000 so I don't have to configure the null value, which might also cause some confusion with some users. Is having a check to see if the `expiresAt` is valid out of the question?

**Comment by erichaus** [comment]
hey @threeaccents @jpadilla, so originally I had set the timeFactor to default to 1 really with the intention that people would either use the default (if their backend returned time in milliseconds) or set it to 1000 if their backend returned time in seconds (e.g. python).

It seems like a few people have been snagged by this so maybe we should update how that's handled? One solution is to default to 1000 but then people with a backend that defaults to milliseconds will get bit (node).

Another simple solution would be to change it to either "seconds" or "milliseconds" with a clear description, or make it null like you suggested and force it's definition in local config...

Any other suggestions?

**Comment by ghost** [comment]
@jpadilla @erichonkanen  I would just change it to 1000 since more people need that setting than 1. Also maybe I would just do a check to make sure its what expiresAt is supposed to be if not throw an error to alert the user. Since if timeFactor is set incorrectly the user is still logged in so the user has no feedback that something went wrong. I can write something up if you guys want. I also made a pull request to change the default to 1000.

**Comment by erichaus** [comment]
not sure if this is related but I just upgraded a project from < 1.6 to latest tagged related 0.7.1 and noticed that refreshing the page is now broken again...

not sure what the breaking change was but I also confirmed that it works fine in 0.6.0 so I'll try to look into that tomorrow!

**Comment by gcasanova** [comment]
Has anyone found a work around for this? I am currently running version 0.7.3, using jwt authenticator and local storage's 'ember_simple_auth:session' key gets reset to an empty '{"secure":{}}' after browser refresh. I have tested with multiple browsers, certainly not a browser specific issue. It's a university project, anyone can take a look at my app configuration here if it helps, https://github.com/gcasanova/SocialDemand-Client. Please help!

**Comment by erichaus** [comment]
@gcasanova there was a fix submitted for issue w/refresh but hasn't been released yet. it's in master branch though, can you try using the latest master and see if it fixes it?

see: https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L176

**Comment by gcasanova** [comment]
@erichonkanen I think that commit is included in the latest release (0.7.3). I can confirm that the authenticator 'jwt.js' file included in the version I am running includes your fix though :(

**Comment by ghost** [comment]
@gcasanova for your refresh fix add this to your config file

`timeFactor: 1000,`

**Comment by erichaus** [comment]
@gcasanova let me know if @threeaccents suggestion fixes it... I'm going to submit a pr that makes that the default since it seems to be a common issue

**Comment by gcasanova** [comment]
Yes, this fixed it. Thanks a lot @threeaccents, much appreciated!

**Comment by ghost** [comment]
@gcasanova np man. @erichonkanen I've already submitted a pr like 3 weeks ago with that change but for some reason when I changed it it made one of the tests fail. I looked into it and it seems to be  a Travis bug with Emberjs because when I run the test on my local machine everything passes. Some other people where experiencing the same problem.

**Comment by erichaus** [comment]
@threeaccents ahh ok.. that's strange, what does the test fail with?

**Comment by ghost** [comment]
@erichonkanen  on Travis it says it fails but when I run the test locally on my machine everything passes. I saw some other people were having the same problem with ember apps.
