### ISSUE TITLE
Readme example

### ISSUE THREAD

**Issue by erichaus** [fenichelar/ember-simple-auth-token#67]
Just curious why the readme switched to showing the non-mixin way to use the token/jwt authenticators? Trying to debug what has changed thats breaking my app after updating various packages including this one and noticed that the simple auth readme shows the mixin version (which I used previously and the readme used to include)

Again mainly asking bc trying to determine what has changed...

```
// app/controllers/login.js
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';

export default Ember.Controller.extend(LoginControllerMixin, {
  authenticator: 'authenticator:custom'
});
```

**Comment by jpadilla** [comment]
See simple-auth 0.8.1-beta.1 [release notes](https://github.com/simplabs/ember-simple-auth/releases/tag/0.8.0-beta.1).

> The LoginControllerMixin and AuthenticationControllerMixin mixins are now deprecated. The invalidateSession and authenticateSession actions in the ApplicationRouteMixin mixin have been deprecated as well. authenticateSession is replaced by the new sessionRequiresAuthentication action

**Comment by erichaus** [comment]
ah ok got it thanks!
