### ISSUE TITLE
Refreshing page in 0.7.1 leads to blank screen

### ISSUE THREAD

**Issue by erichaus** [fenichelar/ember-simple-auth-token#68]
Just dove back into this repo and upgraded from < 0.6.0 to 0.7.1 (with simple auth 0.8.0 beta2) and noticed that if I refresh the page, it leads to a blank screen and frozen app (until I delete the cookie).

I downgraded to 0.6.0 and the refresh functionality works so something possibly broke it or I am missing something? I will continue to look at this during the week!

-E

**Comment by jpadilla** [comment]
@erichonkanen do you it could have been simple-auth's recent breaking change?

> The secure session data is now stored under the special key secure. This makes sure that the session isn't cleared completely on logout but only the secure key instead. This is a [BREAKING] change if you're using a custom authorizer as that must fetch the token etc. from the session's secure key now.

**Comment by erichaus** [comment]
hmm interesting, yeah that could be it.. will look into that in a bit

**Comment by cherta** [comment]
I did have the same issue, I downgraded to 0.6.0 and it seamed "solve" the problem for now. Please let me know if I can be of any help.

**Comment by erichaus** [comment]
@cherta still trying to debug so any extra eyes/brains helps.. def something with latest 0.8.0-beta ember-simple-auth

**Comment by erichaus** [comment]
fixed with https://github.com/jpadilla/ember-cli-simple-auth-token/pull/73
