### ISSUE TITLE
Classes should be importable

### ISSUE THREAD

**Issue by miguelcobain** [fenichelar/ember-simple-auth-token#7]
I was trying to override the token authenticator to customize the `getAuthenticateData` function.
I generated an initializer using ember-cli.

I was expecting to import the token authenticator like this:
`import TokenAuthenticator from 'simple-auth-token/authenticators/token';`

But that didn't work (file not found). Instead I had to do:
`import TokenAuthenticator from 'myapp/authenticators/token';`

Any idea why this happens?

**Comment by jpadilla** [comment]
@miguelcobain not really sure, but I'll look into it. Thanks for reporting

**Comment by jpadilla** [comment]
@miguelcobain I was able to replicate this and I'm trying to figure out why it's not exporting correctly. Must be something to do with the `index.js`.

**Comment by miguelcobain** [comment]
Could we compare with other ember-cli addons like https://github.com/simplabs/ember-cli-simple-auth-devise ? See if we can spot a difference, or if this bug is also present there.
I relatively new to the ember-cli world, but I'll also try to take a look. Thanks!

**Comment by jpadilla** [comment]
I've followed parts of how those were structured, but it's a bit different because mine only works with ember-cli. I'm waiting for some more docs on the new ember addon blueprint to rewrite this using that setup and also get some tests done.

Update: Help is definitely welcome to try and fix the current implementation.

**Comment by knownasilya** [comment]
@jpadilla would also love being able to use this without ember-cli..

**Comment by miguelcobain** [comment]
it shouldn't be to hard. Just include the folder with the built code (result from `ember build`) and create a bower from this repo?

**Comment by kurko** [comment]
@jpadilla you can't import anything that's inside `node_module/`, but you can import what's inside of `bower_components`. `ember-cli-simple-auth` is an addon that sets up itself inside `bower_components`. So I'd say:
1. build the plugin (make it into a single file) and check it into the repo (e.g inside `dist/`)
2. publish the plugin with Bower.
3. we'll be able to `import` it easily.

I have a short deadline for my project and I need it urgently (have to deliver on friday), or else I'll have to fork and publish myself on npm. If you want, I can send a PR with the `bower.json` file.

**Comment by kurko** [comment]
Actually, I take back what I said here. I totally mislooked the description here (and what was being loaded by Ember CLI). The following is good to me.

``` js
import Base from 'your-app-name/authenticators/token';
```

**Comment by jpadilla** [comment]
@kurko I've been working into refactoring this to use the new ember-cli's `ember addon` feature as well as adding tests.

I've created a new branch, [refactor](https://github.com/jpadilla/ember-cli-simple-auth-token/tree/refactor) with the current progress which seems to be working on an example project. All tests are passing.

I'd like some feedback on it and if you could try it out and report any weird things, that'd be awesome.

**Comment by jpadilla** [comment]
Just released [v0.4.0](https://github.com/jpadilla/ember-cli-simple-auth-token/releases/tag/v0.4.0).
