### ISSUE TITLE
Swap type for method in the $.ajax call ?

### ISSUE THREAD

**Issue by toranb** [fenichelar/ember-simple-auth-token#74]
I noticed you are using type instead of method - is this for any specific reason? I'm not entirely sure when jQuery switched this api but for the most part my ajax requests use method and I was curious why you chose type instead of method

https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L290

**Comment by jpadilla** [comment]
According to jQuery docs for [ajax](https://api.jquery.com/jquery.ajax/)

> An alias for method. You should use type if you're using versions of jQuery prior to 1.9.0.

Let's change it to `method` for consistency.

**Comment by toranb** [comment]
Wow just that easy huh? I assumed this might require some docs to update/a deprecation release for those using the library (followed by a point release to update it like you did in #74 above).

Any idea when this will make the next release? Thanks again for fixing it :)

**Comment by jpadilla** [comment]
@toranb this shouldn't have been an issue for anyone as the method/type alias exists since 1.9.

http://bugs.jquery.com/ticket/12004

Did you actually run into issues? What version of jQuery are you using?

**Comment by toranb** [comment]
Understood - just didn't know if this was a truly "black box" or if people using this had monkey patched it in some way/the docs showed it/etc. Clearly I was incorrect (for the good -as this should be an implementation detail in the auth library).

The issue I had w/ this wasn't the fault of simple auth. Instead I was using a specific tdd approach/stub library/qunit module that fails when it resolves a test where 1) an ajax request fired I didn't know about 2) an ajax request didn't fire but I "expected" it should 3) an ajax request fires (that I did expect) but the verb / type (now method) / payload (if POST/PUT/PATCH) didn't match exactly.

My module that does this didn't match correctly on "type" for some reason (even though every scenario I had something like this)

``` js
foo.method || foo.type
```

Regardless - totally my fault trying to tdd like a boss :) 

qunit module below for anyone looking to tdd a little more with xhr like work

https://github.com/toranb/ember-cli-test-helpers/blob/master/test-support/helpers/module.js#L14-L19
