### ISSUE TITLE
Configuration data no longer being read

### ISSUE THREAD

**Issue by jrjohnson** [fenichelar/ember-simple-auth-token#76]
Working with the master branch my app config data is no longer being read.  I'm guessing [38a50ac7cea9ce66b62c35b8a3137cd2789f5e2d] is the reason, but I haven't messed with addon configuration enough to be sure of the fix.

**Comment by steveklabnik** [comment]
I _think_ I am seeing this too

**Comment by steveklabnik** [comment]
yup. this basically means that the README doesn't work

**Comment by jpadilla** [comment]
My bad, that's not needed at all in our setup.  Fixing it right now.

**Comment by steveklabnik** [comment]
🎉🎊🎉🎊 many thanks

**Comment by jrjohnson** [comment]
Agreed.  Thanks!

**Comment by steveklabnik** [comment]
Hmmm, so I figured I should try this, so I switched to HEAD

``` diff
-    "ember-cli-simple-auth-token": "^0.7.2",
+    "ember-cli-simple-auth-token": "jpadilla/ember-cli-simple-auth-token",
```

I have this in my environment.js:

```
 var ENV = {
    // snip!
    'simple-auth': {
      authorizer: 'simple-auth-authorizer:token',
      serverTokenEndpoint: '/shops'
    }
```

yet, it's still trying to hit `http://localhost:4200/api-token-auth/` instead of `/shops`. Am I doing something dumb? Maybe this issue didn't affect me, and I'm just missing something.

**Comment by jpadilla** [comment]
serverTokenEndpoint has to be set in ENV['simple-auth-token']

**Comment by steveklabnik** [comment]
Ah! Thanks. Let me send you a PR...

**Comment by steveklabnik** [comment]
Ahh, no PR needed, I just mis-read the readme :sweat: 

Thanks again!

**Comment by jrjohnson** [comment]
@jpadilla can you tag a release with this fix?

Never mind.  I see it is in NPM, just not a git tag.  Sorry for the ping.
