### ISSUE TITLE
Token not being applied in headers

### ISSUE THREAD

**Issue by awwester** [fenichelar/ember-simple-auth-token#79]
Can't figure out why, but my token is not being applied to my request headers

Accept:application/json, text/javascript, _/_; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:es-ES,es;q=0.8,en;q=0.6
Connection:keep-alive
Host:localhost:8000
Origin:http://localhost:4200
Referer:http://localhost:4200/admin/archive
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

```
//update - added crossOriginWhitelist here but same behavior 
'simple-auth' :{
  crossOriginWhitelist: ['*'],
  authorizer: 'simple-auth-authorizer:token',
  authenticationRoute: 'accounts.login',
  routeAfterAuthentication: 'admin.orders',
  routeIfAlreadyAuthenticated: 'admin.orders',
},

'simple-auth-token': {
  refreshAccessTokens: true,
  timeFactor: 1,
  refreshLeeway: 300,
  tokenAttributeName: 'key',
  authorizationPrefix: 'Token ',
  serverTokenEndpoint: api + '/v1/auth/login/',
},
```

And the response from my serverTokenEndpoint is 200 {"key":"ThisIsMyKey123412341234"}

Any ideas why the token wouldn't be applied? I'm on simple auth 0.8.0, token auth 0.7.2, and ember 1.13.1

**Comment by alekspetrov** [comment]
The same trouble, seems like a bug from #6 issue.

**Comment by jpadilla** [comment]
@awwester @alekspetrov have you tried it on 0.7.3?

**Comment by awwester** [comment]
@jpadilla just upgraded to 0.7.3 and have the same behavior

**Comment by alekspetrov** [comment]
Confirm, 0.7.3 not working

**Comment by jpadilla** [comment]
@alekspetrov @awwester I updated the [demo application](https://jpadilla.github.io/ember-cli-simple-auth-token) which seems to be working correctly. A failing test or reproducible example would definitely help.

**Comment by awwester** [comment]
I'll try to get back to this in the next day or two and have something to show, thanks for the replies.

**Comment by fridaystreet** [comment]
guys, I was scratching my head with this one for a while until I realised I had the wrong port number in my crossOriginWhitelist setting. I must have copied and pasted it from a site. Anyway as soon as I set this to my correct backend port everything started working.

**Comment by awwester** [comment]
after going through source, I found out my problem was that I had `tokenAttributeName` and I needed `tokenPropertyName`. I copied Attribute from another project that uses a different version I suppose. That makes me sad haha.

**Comment by srsgores** [comment]
I'm getting the same problem.  Are any further requests to the API endpoint supposed to include the `Authorization: Bearer` header in them?  If so, will this work with Ember data adapters?  Can anyone describe the process of getting this to work?  My future requests do not have the `Authorization: Bearer` header in them, using Ember Data...

**Comment by alekspetrov** [comment]
@srsgores check your backend response, if it's ok, you should have `crossOriginWhitelist: ['http://yourserverdomain.com']`, in my case it caused the problem.

**Comment by srsgores** [comment]
@alekspetrov I found the problem: note that it's not `crossOriginWhiteList` but `crossOriginWhitelist` (no capital `L`).

**Comment by alekspetrov** [comment]
@srsgores yea, probably in camelCase this should looks like `crossOriginWhiteList` but it's not.
