### ISSUE TITLE
Dependency on Simple Auth

### ISSUE THREAD

**Issue by locks** [fenichelar/ember-simple-auth-token#8]
Why is the dependency on the Simple Auth library not specified in the `package.json`?
I just did `npm install --save-dev ember-cli-simple-auth-token` and I expected it to pull in the necessary libraries, but after running `ember build` I noticed it didn't :P

**Comment by jpadilla** [comment]
@locks thanks for reporting this, I'll try and get to it today. I'm in the process of rewriting how this is packaged using `ember addon <addon-name>` and getting some tests done.

**Comment by jpadilla** [comment]
@locks I've been working into refactoring this to use the new ember-cli's `ember addon` feature as well as adding tests.

I've created a new branch, [refactor](https://github.com/jpadilla/ember-cli-simple-auth-token/tree/refactor) with the current progress which seems to be working on an example project. All tests are passing.

I'd like some feedback on it and if you could try it out and report any weird things, that'd be awesome.

**Comment by jpadilla** [comment]
Just released [v0.4.0](https://github.com/jpadilla/ember-cli-simple-auth-token/releases/tag/v0.4.0).

**Comment by locks** [comment]
@jpadilla I seem to have missed your mention, I'm sorry. I will try `v0.4.0` soon and report back any bugs. Thank you for the update :)
