### ISSUE TITLE
JSON structure

### ISSUE THREAD

**Issue by wolfie82** [fenichelar/ember-simple-auth-token#83]
Is there a way to hook into the JSON structure when posting to the server (receiving as well)?  IE I use the JSON API standard.

**Comment by micahjon** [comment]
+1

**Comment by lbk-msb-fender** [comment]
Would you accept a PR on this?

**Comment by michaelseanbecker** [comment]
Would you accept a PR on this?

**Comment by denkristoffer** [comment]
This would be helpful for integration with [knock](https://github.com/nsarno/knock) for Rails.

**Comment by eluciano11** [comment]
Hi @michaelseanbecker, any is are welcome. I don't think @jpadilla would mind as long as the JSON API serialization is something that can be opt-in by the users of the addon.

@jpadilla thought?

**Comment by jpadilla** [comment]
Isn't this already possible with `getAuthenticateData` and `getResponseData`?

**Comment by ghost** [comment]
@jpadilla can you please explain to me how to modify JSON payload sent to the server without write a custom authenticator in `authenticators` folder?

For example this is what I have now, with default:

`{"identification":"myUsername","password":"myPassword"}`

Now I need something like this:

`{"auth": {"identification":"myUsername","password":"myPassword"}}`

Maybe in `controllers/login.js` in `authenticate()` action?

I'm afraid of write buggy code myself in a custom `authenticators/auth.js` file.

I thought something like this: 

```
authenticate(credentials) {
    const myJSON = JSON.stringify({
      auth: {
        email: credentials.email,
        password: credentials.password
      }
    });
```

but where and when?
