### ISSUE TITLE
Update addon to work with upcoming ESA 1.0

### ISSUE THREAD

**Issue by Libermentix** [fenichelar/ember-simple-auth-token#86]
Hi there,

i briefly checked w/ ESA core team, but 1.0 will have quite a lot of breaking changes. 
I don't know the extend but the problem we have run through could already be solved by renaming the imports and by replacing the simple-auth initializer with the updated one from the current ff-abrams branch (which will be 1.0 eventually). 

I could submit a PR, but have not yet updated the tests. I could do so if necessary. 

My closed issue at ESA for reference: simplabs/ember-simple-auth/issues/603

**Comment by mbcomer** [comment]
:thumbsup:

**Comment by micahjon** [comment]
+1

**Comment by mmahalwy** [comment]
Any luck with this?

**Comment by aansubarkah** [comment]
waiting for the update too

**Comment by mmahalwy** [comment]
@aansubarkah you can use my PR: https://github.com/jpadilla/ember-cli-simple-auth-token/pull/89

**Comment by taddeimania** [comment]
:+1: thanks for this!

**Comment by aansubarkah** [comment]
@mmahalwy thanks for the PR. but now im lost, my authenticate action on login controller complain about this.get('session'). it says undefined. how to fix that? or maybe u have a dummy app as a demo how to use ur PR? many thanks

**Comment by mmahalwy** [comment]
@aansubarkah this is what my controller looks like:

```
actions: {
    authenticate: function() {
      var credentials = this.getProperties('identification', 'password');
      var authenticator = 'simple-auth-authenticator:jwt';

      this.set('signinLoading', true);
      return this.get('session').authenticate(authenticator, credentials).then(() => {
        this.set('signInError', false);
      }, () => {
        this.set('password', '');
        this.set('signInError', true);
        this.set('signinLoading', false);
        return true;
      });
    }
  }
```

Notice, I am not sending action `sessionAuthenticated` as suggested here: https://github.com/simplabs/ember-simple-auth/pull/602#issuecomment-138793579 to manage my redirect, etc.

**Comment by aansubarkah** [comment]
@mmahalwy thanks. i'm adding `session: Ember.inject.service('session'),` as a login controller's property, it works fine but now i'm facing another problems, my request header wont send authorization. how to deal with that?

**Comment by mmahalwy** [comment]
@aansubarkah good question, you add it to your application route:

```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  beforeModel() {}
});
```

Application adapter:

```
import config from '../config/environment';
import Ember from 'ember';
import ActiveModelAdapter from 'active-model-adapter';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default ActiveModelAdapter.extend(DataAdapterMixin, {
  host      : config.apiServer,
  namespace : config.namespace,
  authorizer: 'simple-auth-authorizer:token',
  headers: Ember.computed('session', function() {
    return {
      // 'X-User-Id': this.session.get('user.id'),
      'Accept-Version': config.apiVersion
    };
  })
});
```

**Comment by aansubarkah** [comment]
@mmahalwy i'm using RESTAdapter (with PHP on the Backend), my config like

```
ENV['simple-auth'] = {
        authorizer: 'simple-auth-authorizer:token',
        crossOriginWhitelist: ['http://localhost:8765'],// @todo change this on production server
        store: 'session-store:local-storage'
};

ENV['simple-auth-token'] = {
        serverTokenEndpoint: 'http://localhost:8765/manager/users/token',// @todo change this on production server
        identificationField: 'username',
        passwordField: 'password',
        tokenPropertyName: 'token',
        authorizationPrefix: 'Bearer ',
        authorizationHeaderName: 'Authorization',
        headers: {},
        refreshAccessTokens: true,
        serverTokenRefreshEndpoint: 'http://localhost:8765/manager/users/token',// @todo change this on production server
        tokenExpireName: 'exp',
        refreshLeeway: 0,
        timeFactor: 1000
};
```

Application Adapter:

```
import Ember from 'ember';
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.RESTAdapter.extend(DataAdapterMixin, {
    session: Ember.inject.service('session'),
    authorizer: 'simple-auth-authorizer:token',
    headers: Ember.computed('session', function () {
        return {
            // 'X-User_Id':this.session.get('user.id'),
            //'Accept-Version':config.apiVersion
        };
    }),
    shouldReloadAll: function () {
        return false;
    },
    shouldBackgroundReloadRecord: function () {
        return false;
    },
    namespace: 'manager',   
    host: 'http://localhost:8765',// @todo change this on production server
    ajax: function (url, method, hash) {
        hash = hash || {};
        hash.crossDomain = true;
        hash.xhrFields = {withCredentials: false};
        return this._super(url, method, hash);
    }
});
```

big thanks for your help, but still facing the same problem

**Comment by mmahalwy** [comment]
@aansubarkah sorry, we don't use the DS.RESTAdapter, but i'd suggest looking into the source code of the mixin.

**Comment by aansubarkah** [comment]
@mmahalwy omg! it work now! seems like i had typo on this line
`return this.get(`session.session.authenticated.${this.tokenPropertyName}`);`
feel like i'm the most stupid script kiddie ever!
Thank you again for everything you’ve done. Salamu alaykum

**Comment by mmahalwy** [comment]
@aansubarkah my pleasure! Glad I can help! 
Salam

**Comment by Baukereg** [comment]
I'm having trouble implementing the PR as well. Right after log in, the token is send in the header of any server request just like it should. But when I refresh, the token seems to be gone and I'm redirected to the login route again.

It appears no token information is saved in the locale storage:

```
ember_simple_auth:session:"{"secure":{}}"
```

My config looks like this:

```
ENV['simple-auth'] = {
  authorizer: 'simple-auth-authorizer:token',
  authenticationRoute: 'login',
  routeAfterAuthentication: 'index',
  routeIfAlreadyAuthenticated: 'index'
};

ENV['simple-auth-token'] = {
  refreshAccessTokens: true,
  serverTokenEndpoint: '/api/v1/authenticate/',
  serverTokenRefreshEndpoint: '/api/v1/authenticate/token-refresh/',
  timeFactor: 1000,
  refreshLeeway: 300,
  tokenExpireName: 'exp',
  identificationField: 'identification'
};
```

Right now simple-auth-token is the only thing holding us back from upgrading to Ember 2.0.

**Comment by mmahalwy** [comment]
@Baukereg your config is wrong. It's not renamed and restructured to:

```
'ember-simple-auth': {
      base: {
        store               : 'session-store:local-storage',
        crossOriginWhitelist: [process.env.API_SERVER_URL],
        authorizer          : 'simple-auth-authorizer:token'
      }
    },
```

**Comment by Baukereg** [comment]
Yes, it works now. Thank you very much!

**Comment by mmahalwy** [comment]
@Baukereg my pleasure!

**Comment by Finhas** [comment]
Hi @mmahalwy --

First, thanks for the PR. I'm having an issue with `session.isAuthenticated` returning `[object Undefined]` and I can't seem to figure out why. My application adaptor is  

```javascript

import Ember from 'ember';
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  host      : 'http://localhost:3000/api',
  authorizer: 'simple-auth-authorizer:token',
  headers: Ember.computed('session', function() {
    return {
      'Accept-Version': 'api'
    };
  })
});
```

The api server is responding fine and requests are being returned so I'm assuming its something to do with the session data.

**Comment by Baukereg** [comment]
I'm rather confused! I've developed without any trouble the last 7 days. The PR worked perfectly. But now, after a fresh `npm install`, it's broken.

`jqXHR is not a function`

It seems to happen here:

```
authorize: function authorize(jqXHR) {
  ...
  jqXHR(this.authorizationHeaderName, token);
```

Seems like it's receiving the session token instead.

**Comment by mmahalwy** [comment]
hmmm, it must be what you're passing into authorize. Perhaps starting from there?

**Comment by Finhas** [comment]
It has to do with this update to ember-simple-auth 1.0:
https://github.com/simplabs/ember-simple-auth/commit/cb66815fc55f5b993bb4f11fe45e29d79a8d6091

You can fix it by changing
`ember-simple-auth-token\addon\authorizers\token.js` lines 78 and 86 to

```
  authorize: function(data, block) {
   ....

      block(this.authorizationHeaderName, token);
```

**Comment by mmahalwy** [comment]
@Finhas thanks! I am experiencing the same problem now too after fresh node_modules.

**Comment by mmahalwy** [comment]
@Finhas updated: https://github.com/mmahalwy/ember-cli-simple-auth-token/commit/13bbb01233185a7cb8c1fc73fe54cf4ebeaf57d9

**Comment by mmahalwy** [comment]
hmm seems like things got really broken from this morning's updates... @marcoow it'd be nice to get your eyes on this & the PR

**Comment by mmahalwy** [comment]
false call. Turns out that you HAVE to now define `beforeModel` on your unprotected routes.

**Comment by Baukereg** [comment]
And I had just locked the dependencies to certain commits to get it working again. Ow well, it's 1 a.m so I'd better go to bed.

Thanks for the quick responses guys!

**Comment by Finhas** [comment]
Also, forgot to mention, the config in environment.js was ~~simplified~~ **returned to it's original options** with https://github.com/simplabs/ember-simple-auth/commit/97605bcc15d49bfb974595024b7c5b250a494b76

Nothing drastic, just removed the `base : {}` but it may cause issues

```
'ember-simple-auth': {
        store               : 'session-store:local-storage',
        crossOriginWhitelist: [process.env.API_SERVER_URL],
        authorizer          : 'simple-auth-authorizer:token'
}, 
```

Haven't had the issue of defining `beforeModel` on my unprotected routes yet but will comment on this thread if I do...

**Comment by mmahalwy** [comment]
@Finhas not simplified but returned to it's original options (it never had `base` until the rewrite...)

**Comment by jamesdixon** [comment]
@mmahalwy great job with this. It's working fairly well on my end. One thing that isn't working for me that was previously was the use of a custom `localStorageKey`. Setting that option in the `ember-simple-auth` options no longer works and it default to `ember_simple_auth:session`. Have you tried/run into this?

**Comment by marcoow** [comment]
@jamesdixon: you simply extend your own store from the `localStorage` store, override the key property in that and use the new store instead (a bit like how it's done with Ember Data adapters).

**Comment by mmahalwy** [comment]
@marcoow thanks for jumping in and answering that :)

**Comment by albertovasquez** [comment]
In previous versions the Bearer header would be sent during the refresh request.   I'm not getting that currently as the token is being passed via the payload instead.   Is that the expected behavior or did I miss a step?

**Comment by marcoow** [comment]
@albertovasquez the Bearer token being sent along with the refresh request was a consequence of the auto-authorization mechanism in previous versions but it's not actually part of the spec. The header not being sent anymore is expected and the server should use the token from the payload instead.

**Comment by albertovasquez** [comment]
Thanks @marcoow I appreciate it.  That would explain it.

**Comment by albertovasquez** [comment]
On 401 after a token refresh the user is not redirected anywhere.   It is properly reaching serverTokenRefreshEndpoint but I'm not sure if I'm supposed to override anything to redirect to login after a token refresh attempt.   If I refresh correctly (no 401) everything works smoothly now, just not redirecting on 401.

**Comment by albertovasquez** [comment]
@mmahalwy @marcoow I'm assuming I should be capturing sessionDataUpdated or sessionDataInvalidated when refresh returns 401, but where would I do that?

**Comment by marcoow** [comment]
When the authenticator tries to refresh a token and receives a 401 response it should probably trigger the `sessionDataInvalidated` event.

**Comment by albertovasquez** [comment]
@marcoow so I need to override the token authenticator to listen to, handle, that event.  Or can I do it from application-route-mixin route?

**Comment by marcoow** [comment]
Authenticators trigger that event. The session automatically handles it.

**Comment by albertovasquez** [comment]
I'm not sure then what I am missing.  I get back 401 on token refresh and page stays the same until I refresh.   Works fine on initial authorize.

**Comment by marcoow** [comment]
I don't know much about ember-cli-simple-auth-token actually - all I say is that an authenticator that tries to refresh a token and receives a 401 response should trigger the `sessionDataInvalidated` event which will be handled automatically by the session.

**Comment by albertovasquez** [comment]
Thank you.  I'll try to get to the bottom of it and post my findings.

**Comment by albertovasquez** [comment]
Okay issue seems to be that jwt does not trigger 'sessionDataInvalidated' on refreshAccessToken but it does reject() the promise.   So I added that to my install and it does get handled by the session but I'm redirected to / root instead of /login.  So currently working on that.  Just wanted to submit an update.

**Comment by albertovasquez** [comment]
Leaving this here but will open issue elsewhere seems that sesssionInvalidated gets triggered by server after a sessionDataInvalidated and that clearly directs you to the baseURL as opposed to the login.  Not sure that should be the desired affect, but i'll open that issue with simple-auth.    Thanks will put in a PR for raising the trigger that seems to be missing.

```
sessionInvalidated() {
    if (!Ember.testing) {
      window.location.replace(Configuration.baseURL);
    }
  }
```

updating: https://github.com/simplabs/ember-simple-auth/issues/563 discusses issue.

**Comment by devinus** [comment]
Check out https://github.com/datajohnny/ember-simple-token by @datajohnny for the simple token version of this addon compatible with 1.0.

**Comment by jpadilla** [comment]
#100 was merged and is in master. Would love anyone interested to check it out.
