### ISSUE TITLE
JWT token not sent if API server is on same host but different port

### ISSUE THREAD

**Issue by trapias** [fenichelar/ember-simple-auth-token#88]
As reported at Stackoverflow in http://stackoverflow.com/questions/31967655/simple-auth-token-jwt-authorization-not-setting-authorization-header, the authorization token is not being sent to the API server when I serve the ember app and the API server at two different hosts (localist:8000/api for my apiserver, localhost:4200 for ember served via "ember server").

If I let my API server host the ember app at localhost:8000 (keeping the api server at localhost:8000/api), the authorization token is sent to the server.
It's not a crossOrigin problem to my understanding: the request actually reaches the api server, but without the Authorization header at all.

I use the RESTAdapter, configured like this:

```
export default DS.RESTAdapter.extend({
    host: 'https://localhost:8000',
    namespace: 'api/1'
});
```

You can see my configuration in the cited Stackoverflow question. Is there something I miss in order to let the token be sent to the API server when it's not on the same host as Ember?

**Comment by jrdn91** [comment]
Having same problem, do you need to have both the ember app and server on the same port for simple auth to work?

**Comment by rohanthacker** [comment]
Perhaps you need to whitelist the api with simple auth ? 
I am unable to try this at the moment, please refer link below 
https://github.com/simplabs/ember-simple-auth#cross-origin-authorization

**Comment by trapias** [comment]
@rohanthacker I already had whitelisted my api server, but it actually was a configuration problem: I had to set both crossOriginWhitelist and the authorizer configuration params on ENV['simple-auth'] instead of ENV['simple-auth-token']. 

I think I was misled by reading different samples, @Jordan4jc maybe you also can solve so?
Can close this issue now, thank you anyway!
