### ISSUE TITLE
Add a tag for 0.7.3

### ISSUE THREAD

**Issue by omni5cience** [fenichelar/ember-simple-auth-token#92]
It's a small thing, but it throws me off every time I come by the repo.

If you need a quick refresher, creating the tag is just two commands:
`git tag -a v0.7.3 231e0c6` (That's https://github.com/jpadilla/ember-cli-simple-auth-token/commit/231e0c695de2bf75302c95920454fb9f47a6163a)
Then, assuming you have github set as the origin:
`git push origin v0.7.3`

**Comment by jpadilla** [comment]
Thanks for the heads up
