### ISSUE TITLE
Ember 2.0 Support

### ISSUE THREAD

**Issue by aBuder** [fenichelar/ember-simple-auth-token#93]
Hi,

when we will have an Ember 2.0 implementation?

**Comment by cresg820** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by dmitryt** [comment]
+1

**Comment by erichaus** [comment]
anyone know what we need to do specifically to bring this into ember 2+? ive been away but using this lib for big project and may be able to help push it forward soon...

**Comment by jpadilla** [comment]
@erichonkanen it'd be really helpful if you checked #100 out

**Comment by jpadilla** [comment]
#100 was merged and is in master. Would love anyone interested to check it out.
