### ISSUE TITLE
Token not being sent in headers for subsequent API requests

### ISSUE THREAD

**Issue by jrdn91** [fenichelar/ember-simple-auth-token#96]
I have an express server set up with `passport-local` that handles authentication at a `/auth` endpoint when the ember app posts to it, I use the `jsonwebtoken` package to create a token and pass it back along with the authenticated user info back to the app. The incoming payload looks like this

```
{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoibWF0YXg5MSIsImlkIjoiNTYxNWFjZWM4ODg5NjhkOTBiYjZjYmQyIn0sImlhdCI6MTQ0NDMwNDM2MywiZXhwIjoxNDQ0MzA0NjYzLCJhdWQiOiJ0YXhib3QuY29tIiwiaXNzIjoidGF4Ym90LmNvbSJ9.i-lTIoGuOwbMwq6CWckj15LkoBjERkBUhMx-ywPivLE","user":{"_id":"5615acec888968d90bb6cbd2","username":"matax91","password":"$2a$05$xWoOaGV7YktwjpzxnbVq3.XPqeFDeskiki9eVARjPHMjn0nIrHS4u","__v":0}}
```

And my environment is setup as so

```
ENV['simple-auth-token'] = {
    identificationField: 'identification',
    passwordField: 'password',
    tokenPropertyName: 'token',
    authorizationPrefix: 'JWT ',
    authorizationHeaderName: 'Authorization',
  };
```

But on the other pages of the site, the requests to the existing endpoints do not have an `Authorization` header in them at all.

I tried to add a localstore for the session as well

```
ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:token',
    store: 'simple-auth-session-store:local-storage'
  };
```

But that doesn't seem to send the token in a header either. Do I need to structure my response from the `/auth` endpoint differently?

By the way, in my controller it's the basic controller setup that is in the readme so nothing there is different.

**Comment by ncole458** [comment]
I have same issue with Django, any resolution? I am working towards setting the token after authenticate and adding the token in RESTAdapter as below:

```
headers: Ember.computed('session.data.token', function() {
    var session = this.get('session');
    return {
      Authorization: "Token " + session.get("data.token")
    };
})  
```

My authenticate looks like this so far:

```
    authenticate() {

        var credentials = this.getProperties('identification', 'password');
        var authenticator = 'simple-auth-authenticator:token';

        return this.get('session').authenticate(authenticator, credentials).then(() => {
            var userToken = '4c00b675868eb53c605cb64281b356ace8795c5b'; // TO DO
            this.get('session').set('data.token', userToken);
            this.transitionToRoute('dashboard');
        }, () => {
            return true;
        });

    },      
```

**Comment by GiovanniL19** [comment]
+1 Having the same issue too, any resolution? My configuration looks like this: 

``` javascript
ENV['simple-auth'] = {
    crossOriginWhitelist: ['*'],
    authorizer: 'simple-auth-authorizer:token'
  };
  ENV['simple-auth-token'] = {
    serverTokenEndpoint: 'http://localhost:3002/authenticate',
    crossOriginWhitelist:['*'],
    tokenPropertyName: 'token',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'Authorization'
  };
```

**Comment by svparijs** [comment]
+1 Same issue, still no solutions found how to fix this...

**Comment by ncole458** [comment]
I ended up migrating to oauth2 instead which works well

**Comment by jpadilla** [comment]
Is this still an issue with master which uses latest simple-auth?

**Comment by sammy007** [comment]
It just does not work at all. I don't see Authorization header flying to server on ember data requests.

``` javascript
  ENV['ember-simple-auth'] = {
    authenticationRoute: 'login',
    routeAfterAuthentication: 'dashboard',
    authorizer: 'authorizer:token',
    crossOriginWhitelist: ['*']
  };
  ENV['ember-simple-auth-token'] = {
    identificationField: 'login',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'Authorization',
    refreshAccessTokens: true,
    refreshLeeway: 300,
    timeFactor: 1000
  };
```

``` javascript
import DS from 'ember-data';
import config from '../config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend({
  namespace: 'api',
  authorizer: 'authorizer:token'
});
```

**Comment by sammy007** [comment]
Ok, my bad, I forgot to actually extend adapter with mixin. I see header now.

**Comment by eluciano11** [comment]
Hi @GiovanniL19, your configuration seem to be from a version prior to `ember-simple-auth` 1.0. If you are using or want to use `ember-simple-auth` 1.0 you should change some things in your configuration.
- `ENV['simple-auth']` to `ENV['ember-simple-auth']` and your `authorizer` property should be `authorizer:token` instead of `simple-auth-authorizer:token`. 
- `ENV['ember-simple-auth-token']` to `ENV['ember-simple-auth-token']`. 

Everything else seems fine. Finally, remember to extend your adapter and pass the new `DataAdapterMixin`. 

If your upgrading to `ember-simple-auth` 1.0 this blogpost is very helpful http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10

@jpadilla Just upgraded my app and it's working fine. I'm using `ember-django-adapter` which extends the RESTAdapter.

**Comment by GiovanniL19** [comment]
Thank you @eluciano11 I will try that

**Comment by bmrsny** [comment]
@eluciano11 I followed your comment and the blog post but I am getting a 
No authorizer was configured for Ember Simple Auth - specify one if backend requests need to be authorized.

adatpters/application.js

```
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';


export default DS.RESTAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:application',
  namespace: 'api'
});
```

enviornment.js

```
ENV['ember-simple-auth'] = {
    authorizer: 'authorizer:token'
  };

  ENV['ember-simple-auth-token'] = {
    identificationField: 'email',
    serverTokenEndpoint: '/api/tokens'
  };
```

**Comment by eluciano11** [comment]
Hi @bmrsny , I tried to replicate your error in my app but I couldn't. Have you been able to resolve it?

Here is my configuration, maybe it can help:

```
// Sets up simple auth with token type, after authentication routes and authenticated routes.
  ENV['ember-simple-auth'] = {
    authorizer: 'authorizer:jwt',
    crossOriginWhitelist: ['*'],
    routeAfterAuthentication: 'companies.company.summary'
  };

  // Sets up simple auth with jwt token.
  // Has milisecond for refresh and durantion.
  ENV['ember-simple-auth-token'] = {
    serverTokenEndpoint: ENV.APP.API_HOST + '/api/auth/login/',
    identificationField: 'email',
    passwordField: 'password',
    tokenPropertyName: 'token',
    authorizationPrefix: 'JWT ',
    authorizationHeaderName: 'Authorization',
    serverTokenRefreshEndpoint: ENV.APP.API_HOST + '/api/auth/token/refresh/',
    refreshAccessTokens: true,
    timeFactor: 1000, //miliseconds
    refreshLeeway: 600 // Refresh the token 10 minutes (600s) before it expires.
  };
```

**Comment by bmrsny** [comment]
@eluciano11 No luck yet. Thanks for sharing your config tho.

**Comment by bmrsny** [comment]
@eluciano11  did you setup up an authorizer in `app/authorizers/`

**Comment by eluciano11** [comment]
@bmrsny no, I didn't setup an authorizer. The only other thing that I did was to initialize the service and inject it in to the routes and templates.

**Comment by bmrsny** [comment]
Am i forgetting to initialize something. Does the session need to be injected into all routes to authorize?

`Error while processing route: projects.index Cannot read property 'authorize' of undefined TypeError: Cannot read property 'authorize' of undefined
    at authorize (http://localhost:4200/assets/vendor.js:89884:19)
    at hash.beforeSend (http://localhost:4200/assets/vendor.js:89587:30)... so on`

Thanks for your help @eluciano11 
 DataAdapterMixin doesn't work by itself... 

Using Authorization with AuthenticatedRouteMixin in each route, however, works fine.

**Comment by eluciano11** [comment]
@bmrsny no problem.

Ahh! I added the  `AuthenticatedRouteMixin` to my `application` route. Thanks for clarifying that!

**Comment by nonovd** [comment]
Hello, 
I have this problem as well. I can authenticate but in the following requests, the authorization headers are never sent. 

> ember: 2.3.0
> ember data: 2.3.0
> ember-simple-auth: "git://github.com/simplabs/ember-simple-auth.git"
> ember-simple-auth-token: 1.0.0

Whitout the authorization headers, request is forbidden as it should and is followed by this error:

> Error while processing route: Adapter operation failed Error: Adapter operation failed

#### adapter/application.js

``` javascript
import DS from "ember-data";
import ENV from 'myapp/config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
    authorizer: 'authorizer:token',
    host: ENV.APP.API_HOST,
    namespace: 'api',

    buildURL: function(type, id, record){
        return this._super(type, id, record) + '/';
    },
    shouldBackgroundReloadRecord: function() {
        return false;
    },
    shouldReloadAll: function() {
        return true;
    },
});
```

#### config/environnement.js

``` javascript
    ENV['ember-simple-auth'] = {
      authorizer: 'authorizer:token',
      routeAfterAuthentication: 'app.home',
    };

    ENV['ember-simple-auth-token'] = {
      serverTokenEndpoint: ENV.APP.API_HOST+'/rest-auth/login/',
      identificationField: 'username',
      passwordField: 'password',
      tokenPropertyName: 'key',
      authorizationPrefix: 'Token ',
      authorizationHeaderName: 'Authorization',
    };
```

#### routes/application.js

``` javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    invalidateSession: function() {
       ...
    }
  }
});
```

I tried to add AuthenticatedRouteMixin to the route I want to access but it does nothing more:

``` javascript
import Ember from "ember";
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin,{
    model: function() {
        return this.store.findAll('measurement');
    }
});
```

Am I missing something ? Thank you

**Comment by xanhast** [comment]
We were getting this same issue and it was due to not updating simple auth version correctly.  Check in package.json you should have

```
"ember-simple-auth": "1.0.1",
"ember-simple-auth-token": "1.0.0",
```

and no reference to `ember-cli-simple-auth`

**Comment by eluciano11** [comment]
Hi @nonovd , could you verify what @xanhast suggested? I upgraded my app to use ember 2.3.0 and ember data 2.3.3 and it works correctly with the specifications discussed in this issue.

If your setup is correct try running `rm -rf node_modules bower_components` when that finishes run `npm install && bower install`.

Please verify the network tab on the dev tools, see if your request has a response with an HTTP status code of `403`.

**Comment by nonovd** [comment]
Hi @eluciano11 @xanhast,

Thank you, turns out it was all my fault, nothing wrong with the addon. 

In the token authorizer, the authorize method is : 

``` javascript
  authorize(data = {}, block = () => {}) {
    const token = data[this.tokenPropertyName];
    const prefix = this.authorizationPrefix ? this.authorizationPrefix : '';

    if(this.get('session.isAuthenticated') && !Ember.isEmpty(token)) {
      block(this.authorizationHeaderName, prefix + token);
    }
  }
```

But my token is in : 

``` javascript
const token = data.data.attributes[this.tokenPropertyName];
```

And this is okay:

> "ember-simple-auth": "1.0.1",
> "ember-simple-auth-token": "1.0.0",

**Comment by eluciano11** [comment]
@nonovd no problem.

I later I will update the README to provide a smoother installation process and close this issue.

**Comment by bmrsny** [comment]
@nonovd how did you end up fixing the problem with your `token`
mine is
 data.data.attributes[this.tokenPropertyName]
did you end up defining your token in the library or in env config?

**Comment by nonovd** [comment]
@bmrsny I wrote my own authenticator and authorizer based on the ones of this addon and overrode the **getAuthenticateDate** method of the authenticator and the **authorize** method of the authorizer.

``` javascript
getAuthenticateData(credentials) {
    const authentication = {
      "data": {
        "type": "LoginView",
        "attributes": {
          [this.passwordField]: credentials.password,
          [this.identificationField]: credentials.identification
        }
      }
    };

    return authentication;
  }
```

``` javascript
  authorize(data = {}, block = () => {}) {
    const token = data.data.attributes[this.tokenPropertyName];
    const prefix = this.authorizationPrefix ? this.authorizationPrefix : '';

    if(this.get('session.isAuthenticated') && !Ember.isEmpty(token)) {
      block(this.authorizationHeaderName, prefix + token);
    }
  }
```

**Comment by bmrsny** [comment]
Thanks @nonovd for sharing! I will look into your solution of _getAuthenticateData_ . I like that more than what I am currently doing. I think i have the same overwrite of _authorize_. I can't thank you enough for sharing.

**Comment by NullVoxPopuli** [comment]
I'm having an issue with this, but only on POSTs. GETs correctly include the authorization bearer token.
